---
title: "Bradford sector/cluster analysis: summary and links"
author:
  - name: "Dan Olner"
format: 
  html:
    output-file: "Bradford_summary_July2025"
    fig-width: 8
    fig-height: 8
execute:
  echo: false
  message: false
  warning: false
fig-responsive: false
---

```{r setup}
library(tidyverse)
library(sf)#for geo stuff
library(zoo)#for making smoothed moving averages
library(patchwork)#combine ggplots easily
# library(plotly)#For interactive plots
library(RColorBrewer)

source('../functions/misc_functions.R')
source('../functions/adhoc_functions.R')
#source('functions/misc_functions.R')
#source('functions/adhoc_functions.R')

options(scipen = 999)

#Set ggplot theme
theme_set(theme_light())


```


## Bradford sector / cluster analysis: summary doc

Here are links to sources used to look at Bradford's sectors/clusters in context (all open in new tabs).

1. [Main sector/cluster data doc](https://danolner.github.io/RegionalEconomicTools/quarto_docs/Bradford_sectorclusters_July2025.html){target="_blank"} with a series of data plots 
2. [Full 5 digit SIC employment location quotients](https://danolner.github.io/RegionalEconomicTools/quarto_docs/Bradford_BRES_5digit_LQs_July2025.html){target="_blank"} broken down by parent 2 digit SIC.
3. A set of treemaps showing the relative size of sectors in Bradford (as well as comparing Bradford to other ITL3s in West Yorkshire). These are:
    - Treemap for [BRES job count data (2023) for West Yorkshire ITL3 zones](https://danolner.github.io/RegionalEconomicTools/miscdocs/WYLAs_BRES_treemap.html){target="_blank"} including Bradford - sectors with matching colours. Click to drill down into place then 3 SIC levels (section, 2 digit and 5 digit).
    - Treemap for [Companies House job count data (up to end of June 2025) for West Yorkshire ITL3 zones](https://danolner.github.io/RegionalEconomicTools/miscdocs/WYLAs_CompaniesHouse2025_treemap.html){target="_blank"}.
4. [Companies House map](https://danolner.github.io/companieshouseopen/maps/companieshouse_modal_SICsection_byemployeecount_min10plus_hex1000m_wLADs.html){target="_blank"} showing most common broad sector per 100m^2 hex. This is useful for getting a sense of Bradford's economic geography and the surrounding areas.


