---
title: "South Yorkshire CCI just plots"
author:
  - name: "Dan Olner"
format: 
  html:
    output-file: "SY_MSA_CCI_justplots"
    fig-width: 8
    fig-height: 8
execute:
  echo: false
  message: false
  warning: false
fig-responsive: false
collapse: false
navbar: false
sidebar: false
---

```{r setup}
library(tidyverse)
# library(spdep)
library(sf)#for geo stuff
# library(tmap)#for mapping 
library(zoo)#for making smoothed moving averages
library(patchwork)#combine ggplots easily
library(plotly)#For interactive plots
# # library(ggdist)
# library(tidyr)
# library(distributional)
library(RColorBrewer)

source('../functions/misc_functions.R')
source('../functions/adhoc_functions.R')
#source('functions/misc_functions.R')
#source('functions/adhoc_functions.R')

options(scipen = 999)

#Set ggplot theme
theme_set(theme_light())

# Value for all job cutoffs
# minjobs = 99
minjobs = 1

greplsector = 'CREATIVE'

corecities = readRDS('../data/corecitiesvector.rds')

```


# SOUTH YORKSHIRE AS A WHOLE COMPARED TO SELECTED STRATEGIC AUTHORITIES

## "Frontier" SIC sectors

### BRES frontier sectors

```{r, fig-bresindstrat_itl2}

islq = readRDS('../local/ITL2_lqs_for_indstrat.rds') %>% filter(qg(greplsector,sic_namefrom_indstrat_combo)) %>% mutate(sic_namefrom_indstrat_combo = gsub('CREATIVE: ','',sic_namefrom_indstrat_combo))

yeartoplot = readRDS('../local/ITL2_yeartoplots_for_indstrat.rds') %>% filter(qg(greplsector,sic_namefrom_indstrat_combo)) %>% mutate(sic_namefrom_indstrat_combo = gsub('CREATIVE: ','',sic_namefrom_indstrat_combo))

place = "South Yorkshire"

sectorLQorder <- islq %>% filter(
  DATE == max(DATE),#use latest data
  GEOGRAPHY_NAME == place) %>% 
  arrange(-LQ) %>% 
  select(sic_namefrom_indstrat_combo) %>% 
  pull()

# Tick
# length(sectorLQorder)
# length(unique(sectorLQorder))

#Split by frontier or not

#Turn the sector column into a factor and order by LQs
yeartoplot$sic_namefrom_indstrat_combo <- factor(yeartoplot$sic_namefrom_indstrat_combo, levels = sectorLQorder, ordered = T)

#Remove some LQs
yeartoplot.lqfiltered <- yeartoplot %>% filter(LQ > 0 & LQ < 100, JOBCOUNT >= minjobs)

#Drop any sectors that Bradford now doesn't have after that filter
sectorstokeep <- yeartoplot.lqfiltered %>% filter(GEOGRAPHY_NAME == place) %>% select(sic_namefrom_indstrat_combo) %>% pull

yeartoplot.lqfiltered <- yeartoplot.lqfiltered %>% filter(sic_namefrom_indstrat_combo %in% sectorstokeep)

# Make base layer just of labelled core cities
# Remove sheffield also, don't want that labelled
corecities_baselayer = yeartoplot.lqfiltered %>% filter(qg('manchester|mersey|west mid|west york|north york|east york',GEOGRAPHY_NAME))

# Add in placename abbreviations
corecities_baselayer = corecities_baselayer %>% 
  mutate(
    placename_short = str_sub(GEOGRAPHY_NAME,1,2),
    placename_short = ifelse(qg('west york', GEOGRAPHY_NAME),'WY',placename_short),#Edinburgh
    placename_short = ifelse(qg('west mid', GEOGRAPHY_NAME),'WM',placename_short),#Edinburgh
    placename_short = ifelse(placename_short == 'Gr','Ma',placename_short)#Edinburgh
  )

# debugonce(LQ_baseplot)
p <- LQ_baseplot(df = corecities_baselayer %>% filter(is_frontier == 1), alpha = 0.8, shape = 0, sector_name = sic_namefrom_indstrat_combo, LQ_column = LQ, change_over_time = slope, labelcolumn = placename_short)

p <- addplacename_to_LQplot(df = yeartoplot.lqfiltered %>% filter(is_frontier == 1), plot_to_addto = p, maxLQvalmultiplier = 0.5,
                            placename = place, shapenumber = 16,
                            min_LQ_all_time = min_LQ_all_time,max_LQ_all_time = max_LQ_all_time,#Include minmax
                            value_column = JOBCOUNT, sector_regional_proportion = sector_regional_proportion,
                            region_name = GEOGRAPHY_NAME,
                            sector_name = sic_namefrom_indstrat_combo, change_over_time = slope, LQ_column = LQ,
                            text = 7, value_col_ismoney = F)

p <- p + 
  # coord_cartesian(xlim = c(0.1,7)) +
  ggtitle("IndStrat frontier sector")

p


```

### Companies house frontier sectors

```{r, fig-chindstrat_itl2}


ch_summary = readRDS('../local/ITL2_CH_lqs_for_indstrat.rds') %>% 
  filter(
    qg(greplsector,sic_namefrom_indstrat_combo),
    !is.na(sic_namefrom_indstrat_combo)
    ) %>% mutate(sic_namefrom_indstrat_combo = gsub('CREATIVE: ','',sic_namefrom_indstrat_combo))

yeartoplot.ch = readRDS('../local/ITL2_CH_yeartoplots_for_indstrat.rds') %>%
  filter(
    qg(greplsector,sic_namefrom_indstrat_combo),
    !is.na(sic_namefrom_indstrat_combo)
    ) %>% mutate(sic_namefrom_indstrat_combo = gsub('CREATIVE: ','',sic_namefrom_indstrat_combo))


sectorLQorder <- yeartoplot.ch %>% filter(
  GEOGRAPHY_NAME == place
  # DATE == max(DATE)#use latest data
) %>% 
  arrange(-LQ) %>% 
  select(sic_namefrom_indstrat_combo) %>% 
  pull()


#Turn the sector column into a factor and order by LCR's LQs
yeartoplot.ch$sic_namefrom_indstrat_combo <- factor(yeartoplot.ch$sic_namefrom_indstrat_combo, levels = sectorLQorder, ordered = T)

#Remove some LQs
yeartoplot.lqfiltered.ch <- yeartoplot.ch %>% filter(LQ > 0 & LQ < 100, JOBCOUNT >= minjobs)

# unique(yeartoplot.lqfiltered.ch$sic_namefrom_indstrat_combo)

#Drop any sectors that place now doesn't have after that filter
sectorstokeep <- yeartoplot.lqfiltered.ch %>% filter(GEOGRAPHY_NAME == place) %>% select(sic_namefrom_indstrat_combo) %>% pull

yeartoplot.lqfiltered.ch <- yeartoplot.lqfiltered.ch %>% filter(sic_namefrom_indstrat_combo %in% sectorstokeep)

# Make base layer just of labelled core cities
# Remove sheffield also, don't want that labelled
corecities_baselayer.ch = yeartoplot.lqfiltered.ch %>% filter(qg('manchester|mersey|west mid|west york|north york|east york',GEOGRAPHY_NAME))

# Add in placename abbreviations
corecities_baselayer.ch = corecities_baselayer.ch %>% 
  mutate(
    placename_short = str_sub(GEOGRAPHY_NAME,1,2),
    placename_short = ifelse(qg('west york', GEOGRAPHY_NAME),'WY',placename_short),#Edinburgh
    placename_short = ifelse(qg('west mid', GEOGRAPHY_NAME),'WM',placename_short),#Edinburgh
    placename_short = ifelse(placename_short == 'Gr','Ma',placename_short)#Edinburgh
  )


p1 <- LQ_baseplot(df = corecities_baselayer.ch %>% filter(is_frontier == 1), alpha = 0.8, shape = 0, sector_name = sic_namefrom_indstrat_combo, LQ_column = LQ, change_over_time = slope, labelcolumn = placename_short)
# p1 <- LQ_baseplot(df = yeartoplot.lqfiltered.ch %>% filter(is_frontier == 1), alpha = 0.03, sector_name = sic_namefrom_indstrat_combo, 
#                   LQ_column = LQ, change_over_time = slope)

# debugonce(addplacename_to_LQplot)
p1 <- addplacename_to_LQplot(df = yeartoplot.lqfiltered.ch %>% filter(is_frontier == 1), plot_to_addto = p1, maxLQvalmultiplier = 0.5,
                             placename = place, shapenumber = 16,
                             # min_LQ_all_time = min_LQ_all_time,max_LQ_all_time = max_LQ_all_time,#Include minmax
                             value_column = JOBCOUNT, sector_regional_proportion = sector_regional_proportion,
                             region_name = GEOGRAPHY_NAME,
                             sector_name = sic_namefrom_indstrat_combo, change_over_time = slope, LQ_column = LQ,
                             value_col_ismoney = F, text = 7)
                             # value_col_ismoney = F, text = 7, maxLQvalmultiplier = 2,useplacenameforminmaxdisplay = T, overridetextpos = 14)

p1 <- p1 + 
  # coord_cartesian(xlim = c(0.1,7)) +
  ggtitle("IndStrat frontier sector")

p1


```

## Other industrial strategy SIC sectors

### BRES other sectors

```{r, fig-bresindstrat2_itl2}
#| fig-height: 13


p <- LQ_baseplot(df = corecities_baselayer %>% filter(is_frontier == 0), alpha = 0.8, shape = 0, sector_name = sic_namefrom_indstrat_combo, LQ_column = LQ, change_over_time = slope, labelcolumn = placename_short)

p <- addplacename_to_LQplot(df = yeartoplot.lqfiltered %>% filter(is_frontier == 0), plot_to_addto = p, maxLQvalmultiplier = 0.5,
                            placename = place, shapenumber = 16,
                            min_LQ_all_time = min_LQ_all_time,max_LQ_all_time = max_LQ_all_time,#Include minmax
                            value_column = JOBCOUNT, sector_regional_proportion = sector_regional_proportion,
                            region_name = GEOGRAPHY_NAME,
                            sector_name = sic_namefrom_indstrat_combo, change_over_time = slope, LQ_column = LQ,
                            text = 7, value_col_ismoney = F)

p <- p + 
  # coord_cartesian(xlim = c(0.1,7)) +
  ggtitle("IndStrat other sector")

p


```

### Companies House other sectors

```{r, fig-chindstrat2_itl2}
#| fig-height: 13

p2 <- LQ_baseplot(df = corecities_baselayer.ch %>% filter(is_frontier == 0), alpha = 0.8, shape = 0, sector_name = sic_namefrom_indstrat_combo, LQ_column = LQ, change_over_time = slope, labelcolumn = placename_short)
# p2 <- LQ_baseplot(df = yeartoplot.lqfiltered.ch %>% filter(is_frontier == 0), alpha = 0.03, sector_name = sic_namefrom_indstrat_combo, 
#                   LQ_column = LQ, change_over_time = slope)

# debugonce(addplacename_to_LQplot)
p2 <- addplacename_to_LQplot(df = yeartoplot.lqfiltered.ch %>% filter(is_frontier == 0), plot_to_addto = p2, maxLQvalmultiplier = 0.5,
                             placename = place, shapenumber = 16,
                             # min_LQ_all_time = min_LQ_all_time,max_LQ_all_time = max_LQ_all_time,#Include minmax
                             value_column = JOBCOUNT, sector_regional_proportion = sector_regional_proportion,
                             region_name = GEOGRAPHY_NAME,
                             sector_name = sic_namefrom_indstrat_combo, change_over_time = slope, LQ_column = LQ,
                             value_col_ismoney = F, text = 7)
                             # value_col_ismoney = F, text = 7, maxLQvalmultiplier = 2,useplacenameforminmaxdisplay = T, overridetextpos = 14)

p2 <- p2 + 
  # coord_cartesian(xlim = c(0.1,7)) +
  ggtitle("IndStrat other sector")

p2



```
