---
title: "Yorkshire and The Humber: growth slope plots for ITL3s (November 2025)"
author:
  - name: "Dan Olner"
format: 
  html:
    output-file: "Yorkshire_n_Humber_growthslope_catalogue_November2025"
    fig-width: 8
    fig-height: 8
execute:
  echo: false
  message: false
  warning: false
fig-responsive: false
collapse: false
navbar: false
sidebar: false
---

```{r setup}
library(tidyverse)
library(sf)#for geo stuff
library(tmap)#for mapping
library(zoo)#for making smoothed moving averages
library(patchwork)#combine ggplots easily
library(plotly)#For interactive plots
library(RColorBrewer)

source('../functions/misc_functions.R')
source('../functions/adhoc_functions.R')
#source('functions/misc_functions.R')
#source('functions/adhoc_functions.R')

options(scipen = 999)

#Counting sigs. Statisticians having kittens. Let's do it.
itl3.2digit.cv <- read_csv('../data/regionalGVA/regionalGVA_chainedvolume_ITL3_SIC_2DIGIT_LONG_2023.csv') %>% filter(!qg('agri|Owner-occupiers|membership|activities of households',SIC07_description))

#Add in shorter regional GVA SIC text
shortsectornames <- read_csv('../data/shortsectornames_for_regionalGVA_2digitSICs.csv')

#check match, tick
# table(unique(itl3.2digit.cv$SIC07_description) %in% shortsectornames$SIC07_description)
itl3.2digit.cv <- itl3.2digit.cv %>% 
  left_join(
    shortsectornames, by = 'SIC07_description'
  )


#And for GVA per job
bres.gva.2digit.2023 <- readRDS('../local/data/BRES2024_linkedtoITL3_2025_GVAsiccodes_withgvaattached.rds') %>% 
  filter(JOBCOUNT > 0, !qg('membership|activities of households|agri', SIC07_description)) %>% 
  mutate(gvaperjob = gva / JOBCOUNT)

#check match, tick
# table(unique(bres.gva.2digit.2023$SIC07_description) %in% shortsectornames$SIC07_description)
bres.gva.2digit.2023 <- bres.gva.2digit.2023 %>% 
  left_join(
    shortsectornames, by = 'SIC07_description'
  )

# Do some name tweaking
itl3.2digit.cv = itl3.2digit.cv %>% 
  mutate(
    SIC07_description_shortened = case_when(
      qg('repair personal',SIC07_description_shortened) ~ 'Pers repair',
      qg('machinery repair',SIC07_description_shortened) ~ 'Mach install',
      qg('transp manuf',SIC07_description_shortened) ~ 'Mach/transp',
      qg('head office',SIC07_description_shortened) ~ 'HO/consult',
      qg('cleaning',SIC07_description_shortened) ~ 'Clean/land',
      qg('accomm',SIC07_description_shortened) ~ 'Accom',
      .default = SIC07_description_shortened
    )
  )

# Do some name tweaking
bres.gva.2digit.2023 = bres.gva.2digit.2023 %>% 
  mutate(
    SIC07_description_shortened = case_when(
      qg('repair personal',SIC07_description_shortened) ~ 'Pers repair',
      qg('machinery repair',SIC07_description_shortened) ~ 'Mach install',
      qg('transp manuf',SIC07_description_shortened) ~ 'Mach/transp',
      qg('head office',SIC07_description_shortened) ~ 'HO/consult',
      qg('cleaning',SIC07_description_shortened) ~ 'Clean/land',
      qg('accomm',SIC07_description_shortened) ~ 'Accom',
      .default = SIC07_description_shortened
    )
  )

#Set ggplot theme
theme_set(theme_light())

```

# INTRODUCTION

This page has **growth trend plots for each ITL3 in Yorkshire and Humber** for **GVA and GVA per full time job (a productivity measure)** (both using the 46 sector categories available in the GVA data). These are done for **the full range of data - 2015 to 2023**.

Here's an explanation of what's in the plots below.

-   Linear slopes are found for each sector in each place, and each is compared to (a) all other sectors in that place ("... internal", light blue) and (b) the same sector in all other ITL3s zones in the data ("... to other places", dark blue).
-   For example - looking at one stand-out sector in the first plot for Barnsley: **utilities**. Its GVA has grown significantly more than around 75% of other sectors in Barnsley, and significantly more than around 75% of that sector in other ITL3 zones. Its productivity (measured in GVA per full time job) has grown equally significantly (higher than around 47% of other ITL3s).
-   The x axis gives the **percent of slopes that are significantly different to others** (i.e. 95% confidence intervals don't overlap).
-   The vertical axis lists all sectors in alphabetical order. These labels given information about the **absolute growth trends** for sectors in each place - i.e. whether they have on average been sloping up or down over the whole time period, irrespective of whether significantly higher or lower than other places:
    -   Green text: slope rises over time - growth is on average going up
    -   Red: slope drops over time - growth is on average going down
    -   Bold green and red: the up or down slope is significantly different from zero (faded red and green can't be statitically separated from no change over time).
    -   Text after the sector name is **percent change per year on average** with 95% confidence intervals.

So:

-   To see **whether a sector has been growing or shrinking overall**, use the sector text (green for growth, red for shrinkage, values given for average % change per year)
-   To **compare that sector's trend with other sectors in each place or the same sector in other places**, use the bars in the plot. Note - **these are relative**: a slope could be *relatively* more positive than another, but the sector overall could still be shrinking. For example, ICT has been growing strongly in most places in the UK - but is growth in one place significantly stronger than others? That's what the place and sector slope comparisons try to answer.
