---
title: "Yorkshire and The Humber: growth slope plots for ITL3s (November 2025)"
author:
  - name: "Dan Olner"
format: 
  html:
    output-file: "Yorkshire_n_Humber_growthslope_catalogue_Nov2025"
    fig-width: 8
    fig-height: 8
execute:
  echo: false
  message: false
  warning: false
fig-responsive: false
collapse: false
navbar: false
sidebar: false
---

```{r setup}
library(tidyverse)
library(sf)#for geo stuff
library(tmap)#for mapping
library(zoo)#for making smoothed moving averages
library(patchwork)#combine ggplots easily
library(plotly)#For interactive plots
library(RColorBrewer)

source('../functions/misc_functions.R')
source('../functions/adhoc_functions.R')
#source('functions/misc_functions.R')
#source('functions/adhoc_functions.R')

options(scipen = 999)

#Counting sigs. Statisticians having kittens. Let's do it.
itl3.2digit.cv <- read_csv('../data/regionalGVA/regionalGVA_chainedvolume_ITL3_SIC_2DIGIT_LONG_2023.csv') %>% filter(!qg('agri|Owner-occupiers|membership|activities of households',SIC07_description))

#Add in shorter regional GVA SIC text
shortsectornames <- read_csv('../data/shortsectornames_for_regionalGVA_2digitSICs.csv')

#check match, tick
# table(unique(itl3.2digit.cv$SIC07_description) %in% shortsectornames$SIC07_description)
itl3.2digit.cv <- itl3.2digit.cv %>% 
  left_join(
    shortsectornames, by = 'SIC07_description'
  )


#And for GVA per job
bres.gva.2digit.2023 <- readRDS('../local/data/BRES2024_linkedtoITL3_2025_GVAsiccodes_withgvaattached.rds') %>% 
  filter(JOBCOUNT > 0, !qg('membership|activities of households|agri', SIC07_description)) %>% 
  mutate(gvaperjob = gva / JOBCOUNT)

#check match, tick
# table(unique(bres.gva.2digit.2023$SIC07_description) %in% shortsectornames$SIC07_description)
bres.gva.2digit.2023 <- bres.gva.2digit.2023 %>% 
  left_join(
    shortsectornames, by = 'SIC07_description'
  )

# Do some name tweaking
itl3.2digit.cv = itl3.2digit.cv %>% 
  mutate(
    SIC07_description_shortened = case_when(
      qg('repair personal',SIC07_description_shortened) ~ 'Pers repair',
      qg('machinery repair',SIC07_description_shortened) ~ 'Mach install',
      qg('transp manuf',SIC07_description_shortened) ~ 'Mach/transp',
      qg('head office',SIC07_description_shortened) ~ 'HO/consult',
      qg('cleaning',SIC07_description_shortened) ~ 'Clean/land',
      qg('accomm',SIC07_description_shortened) ~ 'Accom',
      .default = SIC07_description_shortened
    )
  )

# Do some name tweaking
bres.gva.2digit.2023 = bres.gva.2digit.2023 %>% 
  mutate(
    SIC07_description_shortened = case_when(
      qg('repair personal',SIC07_description_shortened) ~ 'Pers repair',
      qg('machinery repair',SIC07_description_shortened) ~ 'Mach install',
      qg('transp manuf',SIC07_description_shortened) ~ 'Mach/transp',
      qg('head office',SIC07_description_shortened) ~ 'HO/consult',
      qg('cleaning',SIC07_description_shortened) ~ 'Clean/land',
      qg('accomm',SIC07_description_shortened) ~ 'Accom',
      .default = SIC07_description_shortened
    )
  )

#Set ggplot theme
theme_set(theme_light())

```





## Barnsley


```{r, fig-Barnsley_plot}
#| fig-width: 8
#| fig-height: 15

itl3 = "Barnsley"


#CV first. No NeweyWest
ynh.2dig <- plotSlopeCounts(
  df = itl3.2digit.cv,
  placename = itl3,
  startdate = 2014,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = value,
  conf_interval = 95
)

ynh.gvaperjob.2dig <- plotSlopeCounts(
  df = bres.gva.2digit.2023,
  placename = itl3,
  startdate = 2015,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = gvaperjob,#Note, this gets log'd in the function, don't do it here
  conf_interval = 95,
  includesectorname_on_axis = T
)

#Axes match - remove from RHS
ynh.gvaperjob.2dig$plot <- ynh.gvaperjob.2dig$plot +
  theme(axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        legend.position = "bottom"
  ) +
  # axis.text.x=element_blank(),
  # axis.ticks.x=element_blank()) +
  guides(fill = F) +
  ggtitle("GVA/FT") 

#And only need the one legend!
ynh.2dig$plot <- ynh.2dig$plot +
  ggtitle("GVA") +
  theme(
    legend.position = "bottom",
    axis.title.y=element_blank()#add this explanation in figure text
  )

ynh.2dig$plot + ynh.gvaperjob.2dig$plot



```





## Bradford


```{r, fig-Bradford_plot}
#| fig-width: 8
#| fig-height: 15

itl3 = "Bradford"


#CV first. No NeweyWest
ynh.2dig <- plotSlopeCounts(
  df = itl3.2digit.cv,
  placename = itl3,
  startdate = 2014,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = value,
  conf_interval = 95
)

ynh.gvaperjob.2dig <- plotSlopeCounts(
  df = bres.gva.2digit.2023,
  placename = itl3,
  startdate = 2015,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = gvaperjob,#Note, this gets log'd in the function, don't do it here
  conf_interval = 95,
  includesectorname_on_axis = T
)

#Axes match - remove from RHS
ynh.gvaperjob.2dig$plot <- ynh.gvaperjob.2dig$plot +
  theme(axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        legend.position = "bottom"
  ) +
  # axis.text.x=element_blank(),
  # axis.ticks.x=element_blank()) +
  guides(fill = F) +
  ggtitle("GVA/FT") 

#And only need the one legend!
ynh.2dig$plot <- ynh.2dig$plot +
  ggtitle("GVA") +
  theme(
    legend.position = "bottom",
    axis.title.y=element_blank()#add this explanation in figure text
  )

ynh.2dig$plot + ynh.gvaperjob.2dig$plot



```





## Calderdale and Kirklees


```{r, fig-CalderdaleandKirklees_plot}
#| fig-width: 8
#| fig-height: 15

itl3 = "Calderdale and Kirklees"


#CV first. No NeweyWest
ynh.2dig <- plotSlopeCounts(
  df = itl3.2digit.cv,
  placename = itl3,
  startdate = 2014,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = value,
  conf_interval = 95
)

ynh.gvaperjob.2dig <- plotSlopeCounts(
  df = bres.gva.2digit.2023,
  placename = itl3,
  startdate = 2015,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = gvaperjob,#Note, this gets log'd in the function, don't do it here
  conf_interval = 95,
  includesectorname_on_axis = T
)

#Axes match - remove from RHS
ynh.gvaperjob.2dig$plot <- ynh.gvaperjob.2dig$plot +
  theme(axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        legend.position = "bottom"
  ) +
  # axis.text.x=element_blank(),
  # axis.ticks.x=element_blank()) +
  guides(fill = F) +
  ggtitle("GVA/FT") 

#And only need the one legend!
ynh.2dig$plot <- ynh.2dig$plot +
  ggtitle("GVA") +
  theme(
    legend.position = "bottom",
    axis.title.y=element_blank()#add this explanation in figure text
  )

ynh.2dig$plot + ynh.gvaperjob.2dig$plot



```





## Doncaster


```{r, fig-Doncaster_plot}
#| fig-width: 8
#| fig-height: 15

itl3 = "Doncaster"


#CV first. No NeweyWest
ynh.2dig <- plotSlopeCounts(
  df = itl3.2digit.cv,
  placename = itl3,
  startdate = 2014,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = value,
  conf_interval = 95
)

ynh.gvaperjob.2dig <- plotSlopeCounts(
  df = bres.gva.2digit.2023,
  placename = itl3,
  startdate = 2015,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = gvaperjob,#Note, this gets log'd in the function, don't do it here
  conf_interval = 95,
  includesectorname_on_axis = T
)

#Axes match - remove from RHS
ynh.gvaperjob.2dig$plot <- ynh.gvaperjob.2dig$plot +
  theme(axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        legend.position = "bottom"
  ) +
  # axis.text.x=element_blank(),
  # axis.ticks.x=element_blank()) +
  guides(fill = F) +
  ggtitle("GVA/FT") 

#And only need the one legend!
ynh.2dig$plot <- ynh.2dig$plot +
  ggtitle("GVA") +
  theme(
    legend.position = "bottom",
    axis.title.y=element_blank()#add this explanation in figure text
  )

ynh.2dig$plot + ynh.gvaperjob.2dig$plot



```





## East Riding of Yorkshire


```{r, fig-EastRidingofYorkshire_plot}
#| fig-width: 8
#| fig-height: 15

itl3 = "East Riding of Yorkshire"


#CV first. No NeweyWest
ynh.2dig <- plotSlopeCounts(
  df = itl3.2digit.cv,
  placename = itl3,
  startdate = 2014,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = value,
  conf_interval = 95
)

ynh.gvaperjob.2dig <- plotSlopeCounts(
  df = bres.gva.2digit.2023,
  placename = itl3,
  startdate = 2015,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = gvaperjob,#Note, this gets log'd in the function, don't do it here
  conf_interval = 95,
  includesectorname_on_axis = T
)

#Axes match - remove from RHS
ynh.gvaperjob.2dig$plot <- ynh.gvaperjob.2dig$plot +
  theme(axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        legend.position = "bottom"
  ) +
  # axis.text.x=element_blank(),
  # axis.ticks.x=element_blank()) +
  guides(fill = F) +
  ggtitle("GVA/FT") 

#And only need the one legend!
ynh.2dig$plot <- ynh.2dig$plot +
  ggtitle("GVA") +
  theme(
    legend.position = "bottom",
    axis.title.y=element_blank()#add this explanation in figure text
  )

ynh.2dig$plot + ynh.gvaperjob.2dig$plot



```





## Leeds


```{r, fig-Leeds_plot}
#| fig-width: 8
#| fig-height: 15

itl3 = "Leeds"


#CV first. No NeweyWest
ynh.2dig <- plotSlopeCounts(
  df = itl3.2digit.cv,
  placename = itl3,
  startdate = 2014,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = value,
  conf_interval = 95
)

ynh.gvaperjob.2dig <- plotSlopeCounts(
  df = bres.gva.2digit.2023,
  placename = itl3,
  startdate = 2015,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = gvaperjob,#Note, this gets log'd in the function, don't do it here
  conf_interval = 95,
  includesectorname_on_axis = T
)

#Axes match - remove from RHS
ynh.gvaperjob.2dig$plot <- ynh.gvaperjob.2dig$plot +
  theme(axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        legend.position = "bottom"
  ) +
  # axis.text.x=element_blank(),
  # axis.ticks.x=element_blank()) +
  guides(fill = F) +
  ggtitle("GVA/FT") 

#And only need the one legend!
ynh.2dig$plot <- ynh.2dig$plot +
  ggtitle("GVA") +
  theme(
    legend.position = "bottom",
    axis.title.y=element_blank()#add this explanation in figure text
  )

ynh.2dig$plot + ynh.gvaperjob.2dig$plot



```





## North and North East Lincolnshire


```{r, fig-NorthandNorthEastLincolnshire_plot}
#| fig-width: 8
#| fig-height: 15

itl3 = "North and North East Lincolnshire"


#CV first. No NeweyWest
ynh.2dig <- plotSlopeCounts(
  df = itl3.2digit.cv,
  placename = itl3,
  startdate = 2014,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = value,
  conf_interval = 95
)

ynh.gvaperjob.2dig <- plotSlopeCounts(
  df = bres.gva.2digit.2023,
  placename = itl3,
  startdate = 2015,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = gvaperjob,#Note, this gets log'd in the function, don't do it here
  conf_interval = 95,
  includesectorname_on_axis = T
)

#Axes match - remove from RHS
ynh.gvaperjob.2dig$plot <- ynh.gvaperjob.2dig$plot +
  theme(axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        legend.position = "bottom"
  ) +
  # axis.text.x=element_blank(),
  # axis.ticks.x=element_blank()) +
  guides(fill = F) +
  ggtitle("GVA/FT") 

#And only need the one legend!
ynh.2dig$plot <- ynh.2dig$plot +
  ggtitle("GVA") +
  theme(
    legend.position = "bottom",
    axis.title.y=element_blank()#add this explanation in figure text
  )

ynh.2dig$plot + ynh.gvaperjob.2dig$plot



```





## North Yorkshire


```{r, fig-NorthYorkshire_plot}
#| fig-width: 8
#| fig-height: 15

itl3 = "North Yorkshire"


#CV first. No NeweyWest
ynh.2dig <- plotSlopeCounts(
  df = itl3.2digit.cv,
  placename = itl3,
  startdate = 2014,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = value,
  conf_interval = 95
)

ynh.gvaperjob.2dig <- plotSlopeCounts(
  df = bres.gva.2digit.2023,
  placename = itl3,
  startdate = 2015,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = gvaperjob,#Note, this gets log'd in the function, don't do it here
  conf_interval = 95,
  includesectorname_on_axis = T
)

#Axes match - remove from RHS
ynh.gvaperjob.2dig$plot <- ynh.gvaperjob.2dig$plot +
  theme(axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        legend.position = "bottom"
  ) +
  # axis.text.x=element_blank(),
  # axis.ticks.x=element_blank()) +
  guides(fill = F) +
  ggtitle("GVA/FT") 

#And only need the one legend!
ynh.2dig$plot <- ynh.2dig$plot +
  ggtitle("GVA") +
  theme(
    legend.position = "bottom",
    axis.title.y=element_blank()#add this explanation in figure text
  )

ynh.2dig$plot + ynh.gvaperjob.2dig$plot



```





## Rotherham


```{r, fig-Rotherham_plot}
#| fig-width: 8
#| fig-height: 15

itl3 = "Rotherham"


#CV first. No NeweyWest
ynh.2dig <- plotSlopeCounts(
  df = itl3.2digit.cv,
  placename = itl3,
  startdate = 2014,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = value,
  conf_interval = 95
)

ynh.gvaperjob.2dig <- plotSlopeCounts(
  df = bres.gva.2digit.2023,
  placename = itl3,
  startdate = 2015,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = gvaperjob,#Note, this gets log'd in the function, don't do it here
  conf_interval = 95,
  includesectorname_on_axis = T
)

#Axes match - remove from RHS
ynh.gvaperjob.2dig$plot <- ynh.gvaperjob.2dig$plot +
  theme(axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        legend.position = "bottom"
  ) +
  # axis.text.x=element_blank(),
  # axis.ticks.x=element_blank()) +
  guides(fill = F) +
  ggtitle("GVA/FT") 

#And only need the one legend!
ynh.2dig$plot <- ynh.2dig$plot +
  ggtitle("GVA") +
  theme(
    legend.position = "bottom",
    axis.title.y=element_blank()#add this explanation in figure text
  )

ynh.2dig$plot + ynh.gvaperjob.2dig$plot



```





## Sheffield


```{r, fig-Sheffield_plot}
#| fig-width: 8
#| fig-height: 15

itl3 = "Sheffield"


#CV first. No NeweyWest
ynh.2dig <- plotSlopeCounts(
  df = itl3.2digit.cv,
  placename = itl3,
  startdate = 2014,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = value,
  conf_interval = 95
)

ynh.gvaperjob.2dig <- plotSlopeCounts(
  df = bres.gva.2digit.2023,
  placename = itl3,
  startdate = 2015,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = gvaperjob,#Note, this gets log'd in the function, don't do it here
  conf_interval = 95,
  includesectorname_on_axis = T
)

#Axes match - remove from RHS
ynh.gvaperjob.2dig$plot <- ynh.gvaperjob.2dig$plot +
  theme(axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        legend.position = "bottom"
  ) +
  # axis.text.x=element_blank(),
  # axis.ticks.x=element_blank()) +
  guides(fill = F) +
  ggtitle("GVA/FT") 

#And only need the one legend!
ynh.2dig$plot <- ynh.2dig$plot +
  ggtitle("GVA") +
  theme(
    legend.position = "bottom",
    axis.title.y=element_blank()#add this explanation in figure text
  )

ynh.2dig$plot + ynh.gvaperjob.2dig$plot



```





## Wakefield


```{r, fig-Wakefield_plot}
#| fig-width: 8
#| fig-height: 15

itl3 = "Wakefield"


#CV first. No NeweyWest
ynh.2dig <- plotSlopeCounts(
  df = itl3.2digit.cv,
  placename = itl3,
  startdate = 2014,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = value,
  conf_interval = 95
)

ynh.gvaperjob.2dig <- plotSlopeCounts(
  df = bres.gva.2digit.2023,
  placename = itl3,
  startdate = 2015,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = gvaperjob,#Note, this gets log'd in the function, don't do it here
  conf_interval = 95,
  includesectorname_on_axis = T
)

#Axes match - remove from RHS
ynh.gvaperjob.2dig$plot <- ynh.gvaperjob.2dig$plot +
  theme(axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        legend.position = "bottom"
  ) +
  # axis.text.x=element_blank(),
  # axis.ticks.x=element_blank()) +
  guides(fill = F) +
  ggtitle("GVA/FT") 

#And only need the one legend!
ynh.2dig$plot <- ynh.2dig$plot +
  ggtitle("GVA") +
  theme(
    legend.position = "bottom",
    axis.title.y=element_blank()#add this explanation in figure text
  )

ynh.2dig$plot + ynh.gvaperjob.2dig$plot



```





## York


```{r, fig-York_plot}
#| fig-width: 8
#| fig-height: 15

itl3 = "York"


#CV first. No NeweyWest
ynh.2dig <- plotSlopeCounts(
  df = itl3.2digit.cv,
  placename = itl3,
  startdate = 2014,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = value,
  conf_interval = 95
)

ynh.gvaperjob.2dig <- plotSlopeCounts(
  df = bres.gva.2digit.2023,
  placename = itl3,
  startdate = 2015,
  enddate = 2023,
  date_colname = year,
  region_colname = Region_name,
  sector_colname = SIC07_description_shortened,
  value_colname = gvaperjob,#Note, this gets log'd in the function, don't do it here
  conf_interval = 95,
  includesectorname_on_axis = T
)

#Axes match - remove from RHS
ynh.gvaperjob.2dig$plot <- ynh.gvaperjob.2dig$plot +
  theme(axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), 
        axis.title.x=element_blank(),
        legend.position = "bottom"
  ) +
  # axis.text.x=element_blank(),
  # axis.ticks.x=element_blank()) +
  guides(fill = F) +
  ggtitle("GVA/FT") 

#And only need the one legend!
ynh.2dig$plot <- ynh.2dig$plot +
  ggtitle("GVA") +
  theme(
    legend.position = "bottom",
    axis.title.y=element_blank()#add this explanation in figure text
  )

ynh.2dig$plot + ynh.gvaperjob.2dig$plot



```


