---
title: "Yorkshire and The Humber: sector plot catalogue (November 2025)"
author:
  - name: "Dan Olner"
format: 
  html:
    output-file: "Yorkshire_n_Humber_sector_catalogue_November2025"
    fig-width: 8
    fig-height: 8
execute:
  echo: false
  message: false
  warning: false
fig-responsive: false
collapse: false
navbar: false
sidebar: false
---

```{r setup}
library(tidyverse)
library(sf)#for geo stuff
library(tmap)#for mapping
library(zoo)#for making smoothed moving averages
library(patchwork)#combine ggplots easily
library(plotly)#For interactive plots
library(RColorBrewer)

source('../functions/misc_functions.R')
source('../functions/adhoc_functions.R')
#source('functions/misc_functions.R')
#source('functions/adhoc_functions.R')

options(scipen = 999)

# Data for this side of reality
itl3.ynh = readRDS('../local/data/itl3ynh.rds')
itl1.summedtoitl3SICs = readRDS('../local/data/itl1summedtoitl3SICs.rds')
bres.gva.2d = readRDS('../local/data/bresgva2d.rds')

ynhshortnames = readRDS('../local/data/ynhshortestnames.rds')

# For mapping
mask = readRDS('../local/ynhmask.rds')
itl3.ynh.zones = readRDS('../local/itl3ynh.rds')

sq = readRDS('../local/data/sq.rds')
hexsummary = readRDS('../local/hexsummary_for_dictionary.rds')

tmap_mode('plot')

```

# INTRODUCTION

This report does two things:

1.  Presents visualisations of economic data for the 43 sector categories available in the ONS GVA by industry data for ITL1-level geographies like Yorkshire and The Humber.
2.  In the 'sector by sector highlight' section, goes through most sectors to pull out some Y&H-relevant points from each of the sector visualisations. These are ordered top to bottom by **how concentrated each sector is in Y&H as a whole** - with those most highly concentrated, on average, at the top. For almost every sector, there are important stories even if *on average* that sector is smaller than other UK regions - subregions within Y&H have huge diversity below the surface.

Each sector category's visualisation has its own section - these are on the right hand side of the page and can be used for navigation, and are also linked in each 'highlight' bullet point where that sector is discussed.

See below for a guide on reading the location quotient plots.

In each set of sector visualisations, there are **four plots**:

1.  The **top plot** shows the **GVA location quotient for Yorkshire and The Humber as a whole** for that sector, with other UK regions shown in squares. **All sections are ordered by this LQ value, with the highest first - i.e. the sector that is on average most concentrated in Y&H**.
2.  The plot below this shows **LQs for each of Y&H's ITL3 zones**, showing the diversity of sector concentration within the region. Many sectors will not have high average LQs at the Y&H level, but some sub-regions here do (and vice-versa). The ITL3 with the highest LQ within the region is at the bottom of the plot.
3.  The third plots show **productivity changes and their origin in GVA and/or job shifts**: they puts percent change in GVA on the X axis against full-time job percent change on the Y axis, with the start end points being the three-year average of 2015/17 to 2021/23. Y&H ITL3s are overlaid in blue (with a two letter label) if this sector makes up 1.5% or more of its economy. Several things can be read here:

-   Any arrow with an endpoint within the **lighter grey diagonal area** has increased its productivity (in terms of GVA per full-time job). Conversely, if the arrow lands in the darker great diagonal, GVA per full-time worker has dropped between those two timepoints.
-   Increases in productivity can come about in three different ways: an arrow pointing Northeast in the lighter diagonal area has seen *both* GVA and job count go up; and arrow pointing Southeast has seen productivity increase through a combination of GVA going up and job count going down; an arrow pointing Southwest (in the light diagonal area) I seen GVA drop proportionally less than jobs, thus still increasing productivity (by this measure).

4.  The last plots are **hexmaps for each sector across Y&H based on employee accounts from the latest Companies House data** (covering the year from September 2024 to October 2025). Each hex shows **LQ sector concentration** **relative to the rest of Yorkshire and Humber** - bluer zones are less concentrated than the Y&H average, red zones more concentrated. A hex is included only if it has 10 or more employees for that sector. (The log of LQ values is used for these maps as it is symmetrical between more or less concentrated. For log LQ, zero is the 'concentration is the same as regional average' value, not 1.)

## Location quotient plot guide

The first two outputs for each section are **location quotient plots**. Here's a guide to reading them:

-   Location quotients show the **ratio of a sector's size within a place compared to a larger geography's average** - in this report, Y&H and its sub-regions are compared to the rest of the UK (minus London, see below). For example, in Y&H, fabricated metal products make up 1.5% of the economy, whereas in the rest of the UK (minus London) it's around 1% - so the LQ is around 1.5.
-   Sectors to the right of the centre line are more concentrated in this region when compared to the national average. (e.g. LQ = 10, it is 10x more concentrated).
-   Green circles have been increasing in concentration over time (larger circles increasing the most)
-   Red circles have been decreasing in concentration over time (larger circles decreasing the most)
-   Black horizontal lines show the min and max of concentration in the data’s history (from 2015 to 2023)
-   Circles and lines can be read together - for example, if a green circle is at the right of this line, sector job concentration has been increasing on average and is continuing.
-   Per ITL3 GVA values and percent of the total zone economy are shown with the place name. These are useful to check sector size versus LQ - for example, a sector like jewellery can have a high LQ (as it does in Sheffield and Birmingham) with very low job counts, because there aren't many jobs in this sector overall in Great Britain.

## Data notes

-   GVA data is from the [latest ONS GVA by industry](https://www.ons.gov.uk/economy/grossvalueaddedgva/datasets/nominalandrealregionalgrossvalueaddedbalancedbyindustry) collection - 2023 is the most recent year. The number of sector categories is slightly different for different geographical scales – to compare ITL1 and ITL3 geographies, ITL1 GVA has been binned into the fewer number of ITL3 SICs. BRES job count data and Companies House data have both been binned into the same SIC categories.

-   LQ plots use 'current price' data, which can be summed to find regional GVA proportions. The percent change job vs percent change GVA plots, on the other hand, use 'chained volume' GVA measures that reflect 'real' economic growth - the GVA percent changes here represent real, not just nominal, economic growth.

-   For the main LQ plots, the ITL1 zone for London has been excluded. This is because the size of London's economy warps location quotients for the rest of the UK. For example, if London is included, LQ values for creative sectors are all below one for everywhere except London.

-   All plots except the maps analyse data between 2015 and 2023, using a three-year moving average.

## SECTOR-BY-SECTOR HIGHLIGHTS

This section goes through the sector catalogue below - in the same order, with the first being Y&H's highest LQ value overall - and picks out some highlights from the plots. A few sectors where nothing notable jumps out are excluded - those are listed at the end.

Each bullet point links to its section - click to jump there.

-   [Manufacturer of furniture and other](add_location_quotient_and_proportions) [manufacture](#manufacture-of-furniture-other-manufacturing){target="_blank"} has the highest overall LQ for Y&H as a whole, and this is mirrored in most of the sub regions where it continues to grow in concentration. In the four regions with the highest concentration, there has been mostly an increasing both GVA and jobs. In Y&H in the latest year, around 70% of this is furniture manufacture not ‘other’ – a higher proportion than all other UK regions. It is also a sector with a broad presence right across the region.
-   [Textiles and apparel](#manufacture-of-textiles-wearing-apparel-and-leather){target="blank"} have a much narrower regional focus in the historic West Yorkshire heartlands.
-   Y&H is second only to the West Midlands in concentration of [basic and fabricated metal products](#manufacture-of-basic-and-fabricated-metal-products), overall. The region is also seeing growth and concentration and in overall GVA, though the picture is mixed – GVA and jobs growth in East Riding Wakefield and North Yorkshire, productivity dropping elsewhere. On the hex map, there is a clear concentrated band of homegrown firms within the sector right across Sheffield and Rotherham. While this sector is about 2% of. Y&H’s economy overall, it is a much more substantial chunk in places like Rotherham (5.5%) and North/Northeast Lincolnshire (4.2%).
-   [Manufacture of wood and paper products](#manufacture-of-wood-and-paper-products-and-printing) and printing is only half the size of fabricated metal, but has a strong and grown presence in several subregions. East riding and Rotherham have both seen large GVA and jobs growth (though not necessarily productivity growth). The hex map suggests this sector’s homegrown presence is rather more diffuse than most, with concentrated pockets right across the region.
-   [Manufacture of petroleum, chemicals and other minerals](#manufacture-of-petroleum-chemicals-and-other-minerals) most likely get that high regional GVA from the sector is very high regional proportions in North Northeast Lincolnshire (18% of its economy) and East Riding (5.6%), though in only two places in Y&H is the sector less than 1.5% of its economy. Well, most places seem to have seen an increasing job numbers, this may not have been matched by productivity increases – though in both east riding and north Northeast Lincolnshire, GVA has risen. The hex map likely is not picking up on externally owned petroleum / chemical companies that make up the larger share of Y&H eastern economies, though reds in West Yorkshire and the northern park of South Yorkshire suggest some homegrown firms.
-   For [manufacture of food, beverages and tobacco](#manufacture-of-food-beverages-and-tobacco), a number of places in Y&H have seen substantial GVA and job increases, mostly in the region’s more rural areas. There is evidence of a split in the trajectory of this sector in Y&H, with more rural areas and York seeing strong growth, well places like Wakefield Barnsley and Bradford have either seen much less strong growth or some shrinkage. The hex map highlights many rural hotspots for these sectors.
-   [Employment and tourism](#employment-activities-tourism-and-security-services) is an awkward sector combination imposed by the GVA data. More work needs to be done to understand the huge growth in the sector in East Riding - now making up nearly 5% of its economy, according to ONS data, and having moved from being much less to much more concentrated than average. This could be done with a combination of BRES and Companies House data.
-   [Warehousing and transport activities](#warehousing-and-transport-support-activities) have seen a steady increasing concentration in certain spots across the region, the most often these jobs have been low value – this can be seen in the percentage increase of jobs in the places where the sector is most concentrated accompanied by low percentage increases or even drops in GVA. Nevertheless, these sectors now make up more than 4% of the Wakefield and Doncaster economies. North north east Lincolnshire it’s not following this trend – jobs in the sector has shrunk by around 33% since 2015/17, though GVA has shrunk even faster.
-   For [finance sectors](#financial-and-insurance-activities), having excluded London from the LQ calculations, Y&H as a whole is second only to Scotland. Narrow LQ bars suggest Y&H has kept this position in fairly stable over time. Finance in Y&H cities is relatively unsurprising (ranging from 9.3% of Sheffield’s economy to 13% of Leeds’) and Bradford’s LQ bar’s stability points toward its finance and banking history. However there is also been concentration growth, particularly rapidly in Doncaster where finance now makes up 4% of its economy. The data is showing this increase in Doncaster arising through GVA, not job number increases – a GVA jump of close to 125% since 2015/17 appears in the data.
-   The power sectors are covered by ‘[electricity, gas, water; sewerage and waste management](#electricity-gas-water-sewerage-and-waste-management)’ and here there is likely some overlap with connected sectors like petroleum, showing up in North Northeast Lincolnshire’s rapid concentration and GVA jump. Barnsley appears as the most transformed over this time period, however – visible and how far it’s LQ concentration has changed and in its jobs and GVA jump. The map of Companies House firms headquartered in Y&H highlights interest in concentration spots across the centre of the region.
-   [Food and beverage service activities](#food-and-beverage-service-activities) have of course been especially hard hit by COVID – though unlike many other places, all Y&H subregions have seen jobs increase overall, mostly productivity has dropped. Two exceptions stand up very clearly – York and North Yorkshire are both on trajectories of increased concentration, GVA and job count.
-   The ‘[education](#education)’ SIC covers both private and public sectors, so this data is a little difficult to parse, but there is a striking pattern across the region. The job versus GVA percent change chart shows mostly GVA growth right across the country, accompanied by a fairly even split in whether jobs grew or shrank. Y&H follows the same pattern. Sheffield sits right in the middle, with modest GVA growth but overall no change in jobs. Given those GVA growth numbers, the bank of red LQ concentration drops is most likely indicating that the sector has been evening out across the country. But this hypothesis could bear some more digging.
-   [Office administration and business support activities](#office-administration-and-business-support-activities) are worth highlighting in part due to the non-core city regions where the sector was clearly growing, but also to mention the opposite direction Rotherham and Wakefield appear to be taking. In Rotherham, there have been large drops in a sector that historically has been a large part of its economy in contrast, Wakefield’s admin/support sectors have more than doubled their job count in the last eight years. The non-core city pattern for this sector is also visible in the hex map, with the exception of central York.
-   The top three [transport sector](#land-water-and-air-transport) places tell two different stories. LQ values have not changed much for Doncaster or North Northeast Lincolnshire. However – again – Wakefield has gone from an average LQ to continue to concentration increase, now 3% of its economy and GVA increases proportionally higher than job increases leading to a large jump in productivity over the last eight years. Firms HQd in Y&H show up on the hex map in Strong bands through Central Y&H and in north north east Lincolnshire.
-   [Residential care](#residential-care-activities) has had productivity increases in several Y&H places – accompanied in Barnsley and Rotherham by job increases too, though in another place is like North Yorkshire job numbers have dropped. The sector is a very large slice of Rotherham’s economy – around 3.5%.
-   In [real estate activities](#real-estate-activities-excluding-imputed-rental) (excluding imputed rent, so not reflecting changes in the private housing market) Barnsley is the clear outlier. It looks like it started from a strong base, but has continued to grow in concentration, job count, GVA and productivity. The sector is now close to 7% of Barnsley’s economy.
-   The overall Y&H LQ for [wholesale trade](#wholesale-trade) has gone up over the last eight years and is now sitting at the outside-London average. This looks like real growth in most non-core city areas of the region (with Leeds static and Sheffield shrinking). In Wakefield (6% of its economy), Bradford (4.9%) and East Riding (4.9%), modest job increases with large GVA jumps shows increased productivity.
-   [Construction of buildings](#construction-of-buildings) has a very similar pattern overall to wholesale trade – now increased to an LQ of one. Those increases have been in a mix of places, both rural and urban (Leeds growing, Sheffield shrinking). Productivity has almost uniformly gone up, although this has come with a mix of job increases and drops. Wakefield once again jumps out with strong productivity growth coming from a GVA and jobs jump. The hex map shows less concentration in urban centres, and an interesting cluster line near the East Riding coast.
-   [Motor trades](#motor-trades) covers both wholesale and retail, and the pattern is quite striking across Y&H and the UK as a whole. GVA per full-time job has been dropping in most places – this is true for the vast majority of places in Y&H. While a few places have been bucking the trend of concentration dropping, only East riding has a jobs and GVA increase, albeit a very small one.
-   [Retail trade](#retail-trade) clearly shows the impact of COVID. Almost everywhere has ended up with fewer jobs than they had eight years ago. These top losses have actually led to productivity jumps in a number of places (where percent change arrows point down but in the lighter grey diagonal). In this data, however, Barnsley appears to be going in the other direction – a productivity in increasing 20% jump in both GVA and jobs. In the hex map, retail jobs are very dense within south and West Yorkshire, but tend to make up a large share of jobs outside urban centres.
-   While [legal and accounting services](#legal-and-accounting-activities) have on average been shrinking in concentration across Y&H, there are some important exceptions. The percent change plot shows jobs, GVA and productivity increasing in Sheffield (now 3.5% of its economy) and East Riding (2.4%). LQ increases in Barnsley and Doncaster indicate positive growth across South Yorkshire.
-   [Specialised construction activities](#specialised-construction-activities) cover all the most common building trades, as well as demolition and site preparation. Most places tend to have a reasonably high concentration of these sectors, as they are needed locally. However, South Yorkshire has a much higher concentration than most other places in Y&H or in the rest of the UK, and it continues to increase. Sheffield (at 3.3% of its economy) has larger construction trades than Leeds (2.65%), but Barnsley (5.8%), Doncaster (4.7%) and Rotherham (6.9%) are higher. Jobs, GVA and productivity have been increasing in Sheffield, Barnsley and Doncaster as well as Wakefield and East Riding. The percent change plot shows that most places in the UK have been going in every possible productivity direction; productivity-wise, Y&H is doing relatively well. The hex map shows the relative concentration of this sector in South and West Yorkshire.
-   The ‘[other professional, scientific and technical](#other-professional-scientific-and-technical-activities)’ sectors have stayed relatively close to the outside London UK average, although Y&H concentration has been dropping slightly. Within Y&H, only Sheffield, Calderdale & Kirklees, Bradford and Wakefield have seen relative concentration go up. Calderdale/Kirklees is the only place where the sector is more than 1% of its economy in Y&H. The hex map suggests a concentration of Y&H based firms in York, and a few other hotspots.
-   [Head offices and management consultancy](#head-offices-and-management-consultancy) has been slowly growing in concentration in the region, though it is still just below the outside London UK average. That concentration growth is happening in most places although the percent for most economies is only around 0.5%. For the four exceptions where it is more concentrated than average, three have remained relatively static over time (Leeds, York, Doncaster). Bradford, however, has had a rapid growth – a small boosting job numbers but a very large GVA increase, the sector is now over 2% of its economy. On the hex map, looking at within Y&H concentration, York stands out.
-   The only notable point from the [postal and courier activities](#postal-and-courier-activities) sectors is in Rotherham – making up 1.7% of its economy, much more than the second highest in the region (Sheffield, 0.9%). This is likely connected to warehousing, distribution and logistics. This is supported by the percent change data – while both jobs and GVA have increased, it is the same pattern as warehousing, where productivity has also dropped. From the hex map, the lack of firms HQ’d in Y&H points to mostly external ownership for this sector.
-   The low Y&H LQ for the [Repair and installation of machinery / equipment](#repair-and-installation-of-machinery-and-equipment) sectors is only part of the story here. Relating to and supporting sectors like fabricated metal products, these sectors have shown a small increase in concentration overall that has happened in most places across Y&H. Doncaster is clearly more specialised in these sectors (1.8% of its economy) and on every metric (concentration, jobs, GVA, productivity) it is seeing increases. The hex map suggests Y&H registered businesses have a higher relative concentration in this sector than others.
-   [Telecommunications and ICT](#telecommunications-information-technology) has historically been lower concentration than average, but it is continuing to go up in Y&H. In all but two sub regions, increased concentration has been coupled with rising productivity (and in everywhere but Bradford, job number increases as well). Some parts of this sector, especially telecoms, can be very capital intensive – changes in output per worker maybe due to increases in capital intensity. For homegrown ICT and telecoms firms, the hex map shows a relative concentration in in the north east side of West Yorkshire and in York.
-   [Civil engineering](#civil-engineering) is another sector where sub-regional specialisms show up despite the Y&H level LQ value being relatively low. There was a split of concentration ups and downs across the region. Sheffield, Bradford, East Riding and Barnsley’s LQs have been rising – but Barnsley stands out in the percent change plot, with a combined GVA/jobs/productivity increase. Barnsley is also one of the places where this sector is a large proportion of the economy (2.7%). Doncaster and North Northeast Lincolnshire’s civil engineering sectors are also above 2% of their economies (though both have seen productivity drops).
-   The ‘[Agriculture, forestry and fishing; mining and quarrying](#agriculture-forestry-and-fishing-mining-and-quarrying)’ sectors are of course much more highly concentrated in North Yorkshire (3.65% of its economy), East Riding (4.6%) and north north east Lincolnshire (1.3%). Everywhere else is a good chunk below 1%. The hex map clearly confirms this, highlighting worthy relative concentration of agricultural firms from Companies House are registered. The percent change plot shows, for East Riding and North Yorkshire equally, that while there has been a very large increase in jobs in the sectors since the start of this data, productivity has dropped. As the arrows for other places in the UK where these sectors are more than 1.5% of their economy, this is a pattern repeated across the country.
-   In Y&H, [architectural and engineering activities](#architectural-and-engineering-activities) have kept a very stable LQ some way below the average for other regions. But places within Y&H have been going in opposite directions. South Yorkshire, Leeds and Wakefield have been increasing their LQs – with the exception of Barnsley, which alongside Bradford has had a quite dramatic drop in the concentration of these sectors since 2015/17. The hex map shows up interesting relative concentrations on the East coast of Lincolnshire as well as around Hull.
-   The [accommodation](#accommodation) sector is mostly very low concentration in Y&H. The exception to this is in the north and east, in York, North Yorkshire and East Riding. This is obvious from the hex map, showing spots across the whole of rural north and east Y&H with high concentrations of this sector.
-   ‘[Research and development; advertising and market research](#research-and-development-advertising-and-market-research)’ is another slightly unwieldy combination of sectors imposed by the data structure, but it picks up some interesting patterns. With generally below average LQ across the region, York, North Yorkshire and Leeds form a broad centre (with Sheffield not far behind). The sectors make up big chunks of both York (2.9%) and North Yorkshire’s (2.25%) economies, and both have seen productivity go up on average (the York with job losses, North Yorkshire with job gains). Homegrown firms on the hex map have a high concentration across Leeds.
-   ‘[Publishing; film and TV production and broadcasting](#publishing-film-and-tv-production-and-broadcasting)’ has seen its LQ drop for Y&H as a whole, possibly due to relative increases elsewhere. But South Yorkshire stands out in the sub regional LQ plot: concentration has been going up in each of its local authorities with Sheffield having the highest concentration just ahead of Rotherham. Leeds, however, has kept a stable LQ ahead of all other Y&H regions.
-   ‘[Manufacture of machinery and transport equipment](#manufacture-of-machinery-and-transport-equipment)’ is actually a very high percent of a few Y&H subregions, despite his overall LQ for Y&H being low. Nowhere has seen their concentration change very dramatically over the time period. However, most places where it is concentrated have seen productivity jumps (though with splits on whether this has included job numbers dropping). East riding is there any place that had a relatively high concentration that has had jobs and GVA both drop.
-   ‘[Manufacture of electronic, optical and electrical products](#manufacture-of-electronic-optical-and-electrical-products)’ has the lowest LQ for Y&H as a whole, but also some important sector strengths and dynamics in the region. Specialism is increasing in some clusters while it decreases elsewhere. South Yorkshire in particular is seeing rises in concentration, where the sectors now make up more than 1% of Doncaster’s economy and around 1.5% of Rotherham’s. Sheffield and Barnsley LQs are also rising, as are North Yorkshire’s, Calderdale Kirklees, and North Northeast Lincolnshire’s. Rotherham has the highest concentration, and productivity in jobs have also been going up there. A South Yorkshire cluster seems evident in the hex map.

Sectors not mentioned: social work; human health activities (too crude a bin to pick up anything useful about health tech - large drops are public sector effects from COVID); gambling and betting sports and recreation activities; public administration/defence; rental and leasing activities; services to buildings and landscapes; creative arts, entertainment and cultural activities; repair of computers, personal and household goods.

## SECTOR CATALOGUE---
