# Code for creating a programmatic QML document for Yorkshire and Humber sector figure combos
# So they can be sorted and referenced correctly
# Things to note about what's going on here:
# The header is its own qmd - everything above the first output, and any loaded code
# We then loop HERE over each relevant sector
# And from that, add to the header text to produce the full qmd file.

library(tidyverse)

# Get the header text
headertext = read_file('quarto_docs/Yorkshire_and_Humber_LQplots_qmdheadertext.qmd')

# Read another to check on formatting of headers
# chk = read_file('quarto_docs/Yorkshire_and_Humber_sectors_Nov2025.qmd')

# Test... tick
# write_file(headertext,'quarto_docs/testquarto.qmd')
# Example heading:
# \n\n\n# GROWTH TRENDS IN GVA, JOBS AND GVA PER JOB\n\n\n## Full data range: 2015 to 2023\n\n\n

# Get data for this side of reality
itl3.ynh = readRDS('local/data/itl3ynh.rds')
itl1.summedtoitl3SICs = readRDS('local/data/itl1summedtoitl3SICs.rds')
bres.gva.2d = readRDS('local/data/bresgva2d.rds')

document = headertext

# Order sector list by the LQs for Y&H as a whole
sectororder = itl1.summedtoitl3SICs %>% 
  filter(qg('humber',Region_name), year == max(year)) %>% 
  arrange(-LQ) %>% 
  pull(SIC07_description)

sectororder = sectororder[!qg("households|personal service|membership|occupiers' imputed", sectororder)]

sectorlist = unique(itl3.ynh$SIC07_description)[!qg("households|personal service|membership|occupiers' imputed",unique(itl3.ynh$SIC07_description))]

sectorlist = factor(sectorlist, levels = sectororder, ordered = T)

for(sector in levels(sectorlist)){
  
  # Main sector heading
  document = paste0(
    document,
      "\n\n\n## ",
      sector,
      "\n\n### LQ gva/job plots\n\n\n"
  )  
  
  # Begin plot
  # Create them
  
  # BLOCK 1 for 3 plots combined
  # Start r block with figure name
  document = paste0(
    document,
    "```{r, fig-",
    gsub('[[:punct:]]| ','',sector),#use sector name for fig, remove punct and spaces
    "}\n#| fig-width: 8\n#| fig-height: 15\n\n"
  )
  
  # Generate outputs ready for including
  document = paste0(
    document,
    'p = ynh_autoplots("',
    sector,
    '")\n\n\n'
    # "plotz[[1]]",
    # "\n\n\n"
  )
  
  document = paste0(
    document,
    read_file('prepcode/plot_ynhtext.R'),
    "\n\n\n"
  )
  
  # End r block / new heading
  document = paste0(
    document,
    "```\n\n\n### Employee % change map 2024/25\n\n\n"
  )
  
  
  
  # BLOCK 2 for map
  # Start r block with figure name
  
  # Change of plan - load pre-generated map image
  document = paste0(
    document,
    "![](../local/outputs/ch_hexmaps_fordictionary/",
    gsub('[[:punct:]]| ','',sector),
    ".jpeg){width=\"700px\"}\n\n"
  )
  
  
  # document = paste0(
  #   document,
  #   "```{r, fig-",
  #   gsub('[[:punct:]]| ','',sector),#use sector name for fig, remove punct and spaces
  #   "_map}\n#| fig-width: 8\n#| fig-height: 9\n\n"
  # )
  
  # Map code
  # document = paste0(
  #   document,
  #   'sector = "',
  #   sector,
  #   '"\n\n',
  #   read_file('prepcode/makemap_ynhtext.R'),
  #   "\n\n\n"
  # )
  
  
  # End r block
  # document = paste0(
  #   document,
  #   "```\n\n\n"
  # )
  
  
}


write_file(document,'quarto_docs/yorkshire_n_humber_LQplotcollections_autogenerated.qmd')
# Can preview if RStudio renders instead
# quarto::quarto_render('quarto_docs/yorkshire_n_humber_LQplotcollections_autogenerated.qmd')

# quarto::quarto_preview('docs/quarto_docs/Yorkshire_n_Humber_sector_dictionary_November2025.html')


