# Code for creating a programmatic QML document for Yorkshire and Humber sector figure combos
# So they can be sorted and referenced correctly
# Things to note about what's going on here:
# The header is its own qmd - everything above the first output, and any loaded code
# We then loop HERE over each relevant sector
# And from that, add to the header text to produce the full qmd file.
library(tidyverse)

# Get the header text
headertext = read_file('quarto_docs/Yorkshire_and_Humber_growthslopeplots_qmdheadertext.qmd')

# Get ITL3 names from arbitrary source...
itl3.ynh = readRDS('local/data/itl3ynh.rds')
ynhitl3names = unique(itl3.ynh$Region_name)

# Alphabetical order, so no favouritism!
ynhitl3names = ynhitl3names[order(ynhitl3names)]

# start document
document = headertext

for(itl3 in ynhitl3names){
  
  # Main sector heading
  document = paste0(
    document,
      "\n\n\n## ",
      itl3,
    "\n\n\n"
  )  
  
  # Begin plot
  # Create them
  
  # BLOCK 1 for 3 plots combined
  # Start r block with figure name
  document = paste0(
    document,
    "```{r, fig-",
    gsub('[[:punct:]]| ','',itl3),#use place name for fig, remove punct and spaces
    "_plot}\n#| fig-width: 8\n#| fig-height: 15\n\n"
  )
  
  # Set the variable name to this loop's value inside the QMD
  document = paste0(
    document,
    'itl3 = "',itl3,'"',
    "\n\n\n"
  )
  
  # Get include code
  document = paste0(
    document,
    read_file('prepcode/plot_ynhgrowthslopes.R'),
    "\n\n\n"
  )
  
  # End r block
  document = paste0(
    document,
    "```\n\n\n"
  )
  
  
}


write_file(document,'quarto_docs/yorkshire_n_humber_itl3_growthslopes_autogenerated.qmd')
# Can preview if RStudio renders instead
# quarto::quarto_render('quarto_docs/yorkshire_n_humber_LQplotcollections_autogenerated.qmd')

# quarto::quarto_preview('docs/quarto_docs/Yorkshire_n_Humber_sector_dictionary_November2025.html')


