<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>yorkshire_humber_sector_highlights_summary – UK regional economics tools and analysis in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-b337f537912f5ab074b938eebad4c5d7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">UK regional economics tools and analysis in R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/DanOlner/RegionalEconomicTools"> 
<span class="menu-text">Github repo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Resources</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../regionalgva_n_bres.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regional GVA and job count data: easy squeezy versions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Intros</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro_gvajobsdata_in_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Intro to using ONS GVA and jobs data in R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">GVA/GDP</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../gdp_gaps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GDP/GVA regional gaps in the UK</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../beattyfothergill.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Beatty &amp; Fothergill on productivity: viz</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Sectors</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sector_locationquotients_and_proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">UK sectors: LQs &amp; proportion plots</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#yorkshire-and-the-humber-sector-by-sector-highlights-summary" id="toc-yorkshire-and-the-humber-sector-by-sector-highlights-summary" class="nav-link active" data-scroll-target="#yorkshire-and-the-humber-sector-by-sector-highlights-summary">Yorkshire and The Humber: Sector-by-Sector Highlights Summary</a>
  <ul class="collapse">
  <li><a href="#section-a-digest-of-the-sector-by-sector-highlights" id="toc-section-a-digest-of-the-sector-by-sector-highlights" class="nav-link" data-scroll-target="#section-a-digest-of-the-sector-by-sector-highlights">Section A: Digest of the Sector-by-Sector Highlights</a>
  <ul class="collapse">
  <li><a href="#manufacturing-strengths" id="toc-manufacturing-strengths" class="nav-link" data-scroll-target="#manufacturing-strengths">Manufacturing strengths</a></li>
  <li><a href="#services-and-logistics" id="toc-services-and-logistics" class="nav-link" data-scroll-target="#services-and-logistics">Services and logistics</a></li>
  <li><a href="#professional-and-technical-services" id="toc-professional-and-technical-services" class="nav-link" data-scroll-target="#professional-and-technical-services">Professional and technical services</a></li>
  <li><a href="#other-notable-sectors" id="toc-other-notable-sectors" class="nav-link" data-scroll-target="#other-notable-sectors">Other notable sectors</a></li>
  <li><a href="#sectors-with-nothing-notable-reported" id="toc-sectors-with-nothing-notable-reported" class="nav-link" data-scroll-target="#sectors-with-nothing-notable-reported">Sectors with nothing notable reported</a></li>
  </ul></li>
  <li><a href="#section-b-key-messages-for-the-yorkshire-and-humber-economy" id="toc-section-b-key-messages-for-the-yorkshire-and-humber-economy" class="nav-link" data-scroll-target="#section-b-key-messages-for-the-yorkshire-and-humber-economy">Section B: Key Messages for the Yorkshire and Humber Economy</a>
  <ul class="collapse">
  <li><a href="#a-diversified-manufacturing-base-but-with-geographic-concentration-risk" id="toc-a-diversified-manufacturing-base-but-with-geographic-concentration-risk" class="nav-link" data-scroll-target="#a-diversified-manufacturing-base-but-with-geographic-concentration-risk">1. A diversified manufacturing base, but with geographic concentration risk</a></li>
  <li><a href="#a-logistics-and-distribution-corridor-is-maturing-but-the-value-question-is-open" id="toc-a-logistics-and-distribution-corridor-is-maturing-but-the-value-question-is-open" class="nav-link" data-scroll-target="#a-logistics-and-distribution-corridor-is-maturing-but-the-value-question-is-open">2. A logistics and distribution corridor is maturing — but the value question is open</a></li>
  <li><a href="#financial-services-are-a-genuine-regional-asset-anchored-by-leeds" id="toc-financial-services-are-a-genuine-regional-asset-anchored-by-leeds" class="nav-link" data-scroll-target="#financial-services-are-a-genuine-regional-asset-anchored-by-leeds">3. Financial services are a genuine regional asset, anchored by Leeds</a></li>
  <li><a href="#south-yorkshires-construction-and-engineering-specialisms-deserve-attention" id="toc-south-yorkshires-construction-and-engineering-specialisms-deserve-attention" class="nav-link" data-scroll-target="#south-yorkshires-construction-and-engineering-specialisms-deserve-attention">4. South Yorkshire’s construction and engineering specialisms deserve attention</a></li>
  <li><a href="#the-barnsley-pattern-an-unexpectedly-dynamic-local-economy" id="toc-the-barnsley-pattern-an-unexpectedly-dynamic-local-economy" class="nav-link" data-scroll-target="#the-barnsley-pattern-an-unexpectedly-dynamic-local-economy">5. The “Barnsley pattern” — an unexpectedly dynamic local economy</a></li>
  <li><a href="#productivity-gains-are-uneven-and-sometimes-come-from-the-wrong-place" id="toc-productivity-gains-are-uneven-and-sometimes-come-from-the-wrong-place" class="nav-link" data-scroll-target="#productivity-gains-are-uneven-and-sometimes-come-from-the-wrong-place">6. Productivity gains are uneven and sometimes come from the wrong place</a></li>
  <li><a href="#tech-and-professional-services-are-growing-but-from-a-low-base" id="toc-tech-and-professional-services-are-growing-but-from-a-low-base" class="nav-link" data-scroll-target="#tech-and-professional-services-are-growing-but-from-a-low-base">7. Tech and professional services are growing but from a low base</a></li>
  <li><a href="#rural-and-coastal-economies-have-distinct-dynamics" id="toc-rural-and-coastal-economies-have-distinct-dynamics" class="nav-link" data-scroll-target="#rural-and-coastal-economies-have-distinct-dynamics">8. Rural and coastal economies have distinct dynamics</a></li>
  <li><a href="#covid-aftershocks-are-still-visible-in-the-data" id="toc-covid-aftershocks-are-still-visible-in-the-data" class="nav-link" data-scroll-target="#covid-aftershocks-are-still-visible-in-the-data">9. COVID aftershocks are still visible in the data</a></li>
  <li><a href="#the-motor-trades-signal-matters-beyond-cars" id="toc-the-motor-trades-signal-matters-beyond-cars" class="nav-link" data-scroll-target="#the-motor-trades-signal-matters-beyond-cars">10. The motor trades signal matters beyond cars</a></li>
  </ul></li>
  <li><a href="#section-c-inter-industry-payment-flow-analysis-supply-chain-locality" id="toc-section-c-inter-industry-payment-flow-analysis-supply-chain-locality" class="nav-link" data-scroll-target="#section-c-inter-industry-payment-flow-analysis-supply-chain-locality">Section C: Inter-Industry Payment Flow Analysis — Supply Chain Locality</a>
  <ul class="collapse">
  <li><a href="#method-in-brief" id="toc-method-in-brief" class="nav-link" data-scroll-target="#method-in-brief">Method in brief</a></li>
  <li><a href="#yorkshire-and-the-humbers-overall-supply-chain-self-sufficiency" id="toc-yorkshire-and-the-humbers-overall-supply-chain-self-sufficiency" class="nav-link" data-scroll-target="#yorkshire-and-the-humbers-overall-supply-chain-self-sufficiency">1. Yorkshire and The Humber’s overall supply chain self-sufficiency</a></li>
  <li><a href="#which-yh-sectors-source-most-locally" id="toc-which-yh-sectors-source-most-locally" class="nav-link" data-scroll-target="#which-yh-sectors-source-most-locally">2. Which Y&amp;H sectors source most locally?</a></li>
  <li><a href="#yhs-position-relative-to-other-regions-sector-by-sector" id="toc-yhs-position-relative-to-other-regions-sector-by-sector" class="nav-link" data-scroll-target="#yhs-position-relative-to-other-regions-sector-by-sector">3. Y&amp;H’s position relative to other regions: sector-by-sector</a></li>
  <li><a href="#the-tradeablenon-tradeable-distinction-in-intermediate-supply-chains" id="toc-the-tradeablenon-tradeable-distinction-in-intermediate-supply-chains" class="nav-link" data-scroll-target="#the-tradeablenon-tradeable-distinction-in-intermediate-supply-chains">4. The tradeable/non-tradeable distinction in intermediate supply chains</a></li>
  <li><a href="#change-over-time-2019-2025-arrow-plot-analysis" id="toc-change-over-time-2019-2025-arrow-plot-analysis" class="nav-link" data-scroll-target="#change-over-time-2019-2025-arrow-plot-analysis">5. Change over time: 2019 → 2025 (arrow plot analysis)</a></li>
  <li><a href="#connecting-supply-chain-locality-to-the-sector-catalogue-findings" id="toc-connecting-supply-chain-locality-to-the-sector-catalogue-findings" class="nav-link" data-scroll-target="#connecting-supply-chain-locality-to-the-sector-catalogue-findings">6. Connecting supply chain locality to the sector catalogue findings</a></li>
  <li><a href="#structural-observations" id="toc-structural-observations" class="nav-link" data-scroll-target="#structural-observations">7. Structural observations</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="yorkshire-and-the-humber-sector-by-sector-highlights-summary" class="level1">
<h1>Yorkshire and The Humber: Sector-by-Sector Highlights Summary</h1>
<p><em>Generated by Claude Code (claude-opus-4-6) on 2026-02-23</em> <em>Source: <a href="https://danolner.github.io/RegionalEconomicTools/quarto_docs/Yorkshire_n_Humber_sector_catalogue_November2025.html#sector-by-sector-highlights">Yorkshire &amp; Humber Sector Catalogue, November 2025</a></em></p>
<hr>
<section id="section-a-digest-of-the-sector-by-sector-highlights" class="level2">
<h2 class="anchored" data-anchor-id="section-a-digest-of-the-sector-by-sector-highlights">Section A: Digest of the Sector-by-Sector Highlights</h2>
<p>The catalogue analyses 43 sector categories across Yorkshire and The Humber (Y&amp;H), ordered by regional location quotient (LQ). Data covers 2015-2023 using three-year moving averages, with Companies House hex maps from September 2024 to October 2025. All LQ comparisons are made against an outside-London UK average.</p>
<section id="manufacturing-strengths" class="level3">
<h3 class="anchored" data-anchor-id="manufacturing-strengths">Manufacturing strengths</h3>
<ul>
<li><strong>Furniture &amp; Other Manufacturing</strong> has the highest overall LQ for Y&amp;H, with broad presence across the entire region and growth in both GVA and jobs in top concentration areas.</li>
<li><strong>Basic &amp; Fabricated Metal Products</strong> places Y&amp;H second only to the West Midlands. Rotherham (5.5% of local economy) and North/Northeast Lincolnshire (4.2%) are key clusters, though productivity performance is mixed — rising in East Riding, Wakefield, and North Yorkshire, falling elsewhere.</li>
<li><strong>Textiles, Wearing Apparel &amp; Leather</strong> retains its historic West Yorkshire heartland but with a much narrower geographic focus.</li>
<li><strong>Petroleum, Chemicals &amp; Other Minerals</strong> is extremely concentrated: 18% of the North/Northeast Lincolnshire economy and 5.6% in East Riding. Employment has generally increased though productivity gains haven’t always followed.</li>
<li><strong>Food, Beverages &amp; Tobacco</strong> shows a split trajectory — strong GVA and jobs growth in rural areas and York, while Wakefield, Barnsley, and Bradford have seen weaker growth or shrinkage.</li>
<li><strong>Wood &amp; Paper Products and Printing</strong> is roughly half the size of fabricated metals, with East Riding and Rotherham experiencing large GVA and jobs growth.</li>
</ul>
</section>
<section id="services-and-logistics" class="level3">
<h3 class="anchored" data-anchor-id="services-and-logistics">Services and logistics</h3>
<ul>
<li><strong>Financial &amp; Insurance Activities</strong>: excluding London, Y&amp;H ranks second only to Scotland. Leeds (13%) and Sheffield (9.3%) anchor the sector. Doncaster is a notable mover — a GVA jump of close to 125% drove its share to 4% of the local economy.</li>
<li><strong>Warehousing &amp; Transport Support Activities</strong> has seen steady concentration increases, particularly in Wakefield and Doncaster (both exceeding 4% of local economy). The concern: job increases are often accompanied by low GVA growth, pointing to low-value work. North/Northeast Lincolnshire is an outlier with ~33% job shrinkage since 2015/17.</li>
<li><strong>Land, Water &amp; Air Transport</strong>: Wakefield stands out with GVA increases proportionally higher than jobs increases, yielding a large productivity jump, now 3% of its economy.</li>
<li><strong>Wholesale Trade</strong>: regional LQ has risen to the outside-London average. Wakefield (6%), Bradford (4.9%), and East Riding (4.9%) show “modest job increases with large GVA jumps” — a productivity story.</li>
<li><strong>Postal &amp; Courier Activities</strong>: Rotherham (1.7% of economy) is the standout, likely connected to the wider warehousing/distribution/logistics corridor.</li>
</ul>
</section>
<section id="professional-and-technical-services" class="level3">
<h3 class="anchored" data-anchor-id="professional-and-technical-services">Professional and technical services</h3>
<ul>
<li><strong>Specialised Construction Activities</strong> is notably strong in South Yorkshire: Barnsley (5.8%), Doncaster (4.7%), Rotherham (6.9%). Jobs, GVA, and productivity are all increasing in several of these places. Y&amp;H is doing relatively well on productivity compared to the rest of the UK.</li>
<li><strong>Head Offices &amp; Management Consultancy</strong> shows slowly growing regional concentration, still below outside-London average. Bradford is a standout with rapid growth and a very large GVA increase, now over 2% of its economy.</li>
<li><strong>Telecommunications &amp; IT</strong> has historically lower concentration but is trending upward. All but two sub-regions have coupled increased concentration with rising productivity.</li>
<li><strong>Legal &amp; Accounting Services</strong> show average shrinking concentration, but Sheffield bucks the trend — jobs, GVA, and productivity all increasing, now 3.5% of its economy.</li>
</ul>
</section>
<section id="other-notable-sectors" class="level3">
<h3 class="anchored" data-anchor-id="other-notable-sectors">Other notable sectors</h3>
<ul>
<li><strong>Retail Trade</strong>: almost everywhere has ended up with fewer jobs than eight years ago (COVID impact). Barnsley is the exception with a 20% jump in both GVA and jobs.</li>
<li><strong>Motor Trades</strong>: GVA per full-time job has been dropping in most places across Y&amp;H and the UK — a striking and widespread pattern.</li>
<li><strong>Food &amp; Beverage Services</strong>: unlike most of the UK, all Y&amp;H subregions have seen jobs increase overall. York and North Yorkshire show increasing concentration, GVA, and job count.</li>
<li><strong>Real Estate</strong>: Barnsley is a clear outlier with continued growth in concentration, jobs, GVA, and productivity — close to 7% of its economy.</li>
<li><strong>Agriculture, Forestry, Fishing; Mining &amp; Quarrying</strong>: highly concentrated in North Yorkshire (3.65%), East Riding (4.6%), and North/Northeast Lincolnshire (1.3%). Very large jobs increases have come with productivity drops — a pattern repeated across the UK.</li>
<li><strong>Electronic, Optical &amp; Electrical Products</strong>: lowest overall Y&amp;H LQ, but a South Yorkshire cluster is emerging — Rotherham (~1.5%) with both productivity and jobs going up, and Doncaster over 1%.</li>
<li><strong>Civil Engineering</strong>: Barnsley stands out with combined GVA/jobs/productivity increases, now 2.7% of its economy.</li>
<li><strong>Office Administration &amp; Business Support</strong>: Wakefield’s admin/support sectors more than doubled their job count in eight years. Rotherham has seen large drops.</li>
<li><strong>Employment Activities; Tourism &amp; Security Services</strong>: East Riding shows massive growth, now nearly 5% of its economy.</li>
</ul>
</section>
<section id="sectors-with-nothing-notable-reported" class="level3">
<h3 class="anchored" data-anchor-id="sectors-with-nothing-notable-reported">Sectors with nothing notable reported</h3>
<p>Social work; human health activities; gambling/sports/recreation; public administration/defence; rental and leasing; services to buildings/landscapes; creative arts/entertainment/cultural activities; repair of computers/personal/household goods.</p>
<hr>
</section>
</section>
<section id="section-b-key-messages-for-the-yorkshire-and-humber-economy" class="level2">
<h2 class="anchored" data-anchor-id="section-b-key-messages-for-the-yorkshire-and-humber-economy">Section B: Key Messages for the Yorkshire and Humber Economy</h2>
<section id="a-diversified-manufacturing-base-but-with-geographic-concentration-risk" class="level3">
<h3 class="anchored" data-anchor-id="a-diversified-manufacturing-base-but-with-geographic-concentration-risk">1. A diversified manufacturing base, but with geographic concentration risk</h3>
<p>Claude: Y&amp;H retains genuine manufacturing strength — furniture, metals, chemicals, food — placing it at or near the top of UK regions in several categories. However, these strengths are often hyper-local: petroleum/chemicals in North/Northeast Lincolnshire, metals in Rotherham/Sheffield, textiles in West Yorkshire. This means regional averages can mask both the significance and the vulnerability of these clusters.</p>
<p>Dan: I don’t think ‘local’ means vulnerable always e.g.&nbsp;Rotherham’s strengths have deep history; that makes it a strength for the region.</p>
</section>
<section id="a-logistics-and-distribution-corridor-is-maturing-but-the-value-question-is-open" class="level3">
<h3 class="anchored" data-anchor-id="a-logistics-and-distribution-corridor-is-maturing-but-the-value-question-is-open">2. A logistics and distribution corridor is maturing — but the value question is open</h3>
<p>Claude: Warehousing, transport, wholesale, and postal/courier activities are all growing across a central Y&amp;H belt (Wakefield, Doncaster, Rotherham). Job creation has been strong. The persistent concern is that much of this growth is “low value” — jobs increasing faster than GVA, meaning productivity per worker is flat or falling. Wakefield’s land/water/air transport sector is a counter-example where productivity has jumped, suggesting higher-value logistics activity is possible but not guaranteed.</p>
<p>Dan: this does show up as ‘many jobs, poor productivity’ in several places across the region, and has been policy e.g.&nbsp;in Wakefield to actively go that way. Where does it go next?</p>
</section>
<section id="financial-services-are-a-genuine-regional-asset-anchored-by-leeds" class="level3">
<h3 class="anchored" data-anchor-id="financial-services-are-a-genuine-regional-asset-anchored-by-leeds">3. Financial services are a genuine regional asset, anchored by Leeds</h3>
<p>Claude: Y&amp;H is second only to Scotland (excluding London) in financial services concentration. Leeds and Sheffield are the anchors, but Doncaster’s rapid GVA growth (125% jump) hints at geographic spread. This is one of the region’s strongest service-sector stories and a counterweight to the manufacturing narrative.</p>
<p>Dan: note also in the IS-8 how strongly Calderdale shows up (and Rotherham has jobs concentration growth in this sector).</p>
</section>
<section id="south-yorkshires-construction-and-engineering-specialisms-deserve-attention" class="level3">
<h3 class="anchored" data-anchor-id="south-yorkshires-construction-and-engineering-specialisms-deserve-attention">4. South Yorkshire’s construction and engineering specialisms deserve attention</h3>
<p>Claude: Specialised construction in Barnsley, Doncaster, and Rotherham is at levels (5-7% of local economies) well above the regional and national norm, with productivity increasing. Civil engineering in Barnsley is following a similar upward trajectory.</p>
<p>Dan: this also shows up in the IS-8 ‘foundational’ sector being very strongly concentrated across the whole region, though in different subsectors e.g.&nbsp;more petro-chemical on the coast.</p>
</section>
<section id="the-barnsley-pattern-an-unexpectedly-dynamic-local-economy" class="level3">
<h3 class="anchored" data-anchor-id="the-barnsley-pattern-an-unexpectedly-dynamic-local-economy">5. The “Barnsley pattern” — an unexpectedly dynamic local economy</h3>
<p>Claude: Barnsley appears repeatedly as an outlier: real estate (close to 7% of economy), retail (20% GVA and jobs jump while everywhere else shrank), specialised construction (5.8%), civil engineering (2.7%), electricity/gas/waste (jobs and GVA jump). Whether this reflects genuine diversification, base effects from a smaller economy, or specific large investments deserves further investigation.</p>
<p>Dan: though it also does <em>not</em> show up so strongly in the IS-8 for digital, which includes digital-relevant manufacturing sectors (Leeds and Sheffield both strong for this IS-8).</p>
</section>
<section id="productivity-gains-are-uneven-and-sometimes-come-from-the-wrong-place" class="level3">
<h3 class="anchored" data-anchor-id="productivity-gains-are-uneven-and-sometimes-come-from-the-wrong-place">6. Productivity gains are uneven and sometimes come from the wrong place</h3>
<p>Claude: Several sectors show “productivity increases” that are actually driven by job losses rather than GVA growth (retail is the clearest example). Genuine productivity stories — where both GVA and output per worker are rising — are more common in wholesale trade, specialised construction, telecom/IT, and parts of finance. The data structure makes it important to distinguish between these two routes to higher productivity.</p>
<p>Dan: Finance is tricky here - that huge Doncaster GVA increase not accompanied by jobs growth, and finance shows up as one of the least supply-chain-connected sectors, with capital leaving regions.</p>
</section>
<section id="tech-and-professional-services-are-growing-but-from-a-low-base" class="level3">
<h3 class="anchored" data-anchor-id="tech-and-professional-services-are-growing-but-from-a-low-base">7. Tech and professional services are growing but from a low base</h3>
<p>Claude: Telecom/IT concentration is rising across almost all sub-regions, with productivity increasing too. Head offices and management consultancy are slowly growing. But Y&amp;H remains below the outside-London average in most of these categories. The direction of travel is positive; the absolute position is still catching up.</p>
<p>Dan: a mixed picture, with Sheffield and Leeds both strong in raw terms and a list of other places seeing jobs growth and shrinkage.</p>
</section>
<section id="rural-and-coastal-economies-have-distinct-dynamics" class="level3">
<h3 class="anchored" data-anchor-id="rural-and-coastal-economies-have-distinct-dynamics">8. Rural and coastal economies have distinct dynamics</h3>
<p>Claude: North Yorkshire, East Riding, and North/Northeast Lincolnshire repeatedly appear with different patterns from the urban centres. Agriculture, accommodation, food/beverage services, and petroleum/chemicals drive these economies. The agriculture sector’s large jobs increases coupled with productivity drops is a national pattern that deserves policy attention — more people working for less output per head.</p>
<p>Dan: That ‘job increase plus no output increase’ issue is real across the region, if the GVA data is right, but I’m not sure it passes the smell test. Be careful with this one. Also important to see the rural/coastal differences in the IS-8 foundational sectors.</p>
</section>
<section id="covid-aftershocks-are-still-visible-in-the-data" class="level3">
<h3 class="anchored" data-anchor-id="covid-aftershocks-are-still-visible-in-the-data">9. COVID aftershocks are still visible in the data</h3>
<p>Claude: Food and beverage services, retail, and accommodation all show COVID disruption in their trajectories. Y&amp;H’s food and beverage sector is notable for having recovered job numbers across all subregions — an achievement not replicated everywhere in the UK.</p>
<p>Dan: a really larger part of York and North Yorks’ economies, and both those places have seen real productivity growth along with jobs growth.</p>
</section>
<section id="the-motor-trades-signal-matters-beyond-cars" class="level3">
<h3 class="anchored" data-anchor-id="the-motor-trades-signal-matters-beyond-cars">10. The motor trades signal matters beyond cars</h3>
<p>Claude: The widespread drop in GVA per full-time worker in motor trades is a UK-wide phenomenon visible across Y&amp;H. As a bellwether for consumer-facing service productivity, this trend is worth monitoring as an indicator of broader cost-of-living and consumer spending pressures.</p>
<p>Dan: a really large chunk of Y&amp;H’s whole economy, and a very mixed picture - again, ups and downs for GVA but mostly downs for job count.</p>
<hr>
</section>
</section>
<section id="section-c-inter-industry-payment-flow-analysis-supply-chain-locality" class="level2">
<h2 class="anchored" data-anchor-id="section-c-inter-industry-payment-flow-analysis-supply-chain-locality">Section C: Inter-Industry Payment Flow Analysis — Supply Chain Locality</h2>
<p><em>Generated by Claude Code (claude-opus-4-6) on 2026-02-23</em> <em>Source: HMRC inter-industry payment flow data (ITL2 × SIC section), 2019–2025, analysed via regional input-output coefficient matrices</em></p>
<p>This section uses business-to-business payment flows between UK regions to measure how locally each sector sources its inputs and receives its payments. It complements the sector catalogue (Sections A and B above) by revealing the <strong>intermediate supply chain structure</strong> behind each sector — not what a sector produces or employs, but where the money flows when businesses buy from each other.</p>
<section id="method-in-brief" class="level3">
<h3 class="anchored" data-anchor-id="method-in-brief">Method in brief</h3>
<p>For each region, technical coefficients are calculated: the share of sector <em>i</em>’s total intermediate purchases that go to sector <em>j</em>, split into payments staying within the region (“internal”) versus leaving it (“external”). Two summary measures emerge:</p>
<ul>
<li><strong>Payer locality</strong>: Of all inputs purchased by a sector, what share is sourced from within the same region? (How locally does the sector buy?)</li>
<li><strong>Payee locality</strong>: Of all payments received by a sector from other sectors, what share comes from within the same region? (How locally is the sector served?)</li>
</ul>
<p>Northern Ireland is excluded throughout due to its distinct cross-border payment dynamics.</p>
<hr>
</section>
<section id="yorkshire-and-the-humbers-overall-supply-chain-self-sufficiency" class="level3">
<h3 class="anchored" data-anchor-id="yorkshire-and-the-humbers-overall-supply-chain-self-sufficiency">1. Yorkshire and The Humber’s overall supply chain self-sufficiency</h3>
<p>Y&amp;H sources approximately <strong>21.3%</strong> of its inter-industry purchases from within the region (2025 data), placing it 6th out of 11 GB regions — squarely mid-table. This is a modest increase from 19.6% in 2019, suggesting a slight trend toward greater internal sourcing.</p>
<p>For context, the regional hierarchy is: - <strong>London</strong> (45.9%) — in a league of its own, with nearly half of all B2B payments staying within the capital - <strong>Scotland</strong> (32.1%) and <strong>North West</strong> (27.6%) — the only other regions above 25% - <strong>Y&amp;H</strong> (21.3%) sits in a cluster with Wales (22.0%), West Midlands (22.6%), South West (20.6%) - <strong>North East</strong> (18.5%) and <strong>East Midlands</strong> (18.2%) are the least self-sufficient</p>
<p>The self-sufficiency ranking broadly tracks region size and economic diversity. London’s dominance reflects its vast, dense service economy where many supplier–customer relationships can be satisfied internally. Y&amp;H’s mid-table position is consistent with a region that has genuine economic breadth (manufacturing, finance, logistics) but lacks the critical mass of London, Scotland, or the North West.</p>
<p><strong>Change over time (2019 → 2022 → 2025):</strong> Y&amp;H rose from 19.6% to 21.6% to 21.3% — a step up between 2019 and 2022 that has since plateaued. Wales and North West showed stronger upward trends over the same period. Scotland actually declined slightly (33.2% → 32.1%).</p>
</section>
<section id="which-yh-sectors-source-most-locally" class="level3">
<h3 class="anchored" data-anchor-id="which-yh-sectors-source-most-locally">2. Which Y&amp;H sectors source most locally?</h3>
<p>Within Y&amp;H, the sectors with the highest share of locally-sourced intermediate inputs are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Sector</th>
<th>Internal share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mining/quarrying</td>
<td>49.6%</td>
</tr>
<tr class="even">
<td>Agriculture</td>
<td>42.7%</td>
</tr>
<tr class="odd">
<td>Education</td>
<td>37.4%</td>
</tr>
<tr class="even">
<td>Public administration/defence</td>
<td>36.0%</td>
</tr>
<tr class="odd">
<td>Real estate</td>
<td>35.7%</td>
</tr>
<tr class="even">
<td>Water/waste</td>
<td>34.1%</td>
</tr>
<tr class="odd">
<td>Entertainment</td>
<td>33.3%</td>
</tr>
<tr class="even">
<td>Construction</td>
<td>31.3%</td>
</tr>
<tr class="odd">
<td>Food/beverage service</td>
<td>29.6%</td>
</tr>
<tr class="even">
<td>Manufacturing</td>
<td>28.4%</td>
</tr>
</tbody>
</table>
<p>And those sourcing least locally:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Sector</th>
<th>Internal share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Health/social work</td>
<td>12.9%</td>
</tr>
<tr class="even">
<td>Power/energy</td>
<td>13.3%</td>
</tr>
<tr class="odd">
<td>Finance/insurance</td>
<td>14.6%</td>
</tr>
<tr class="even">
<td>Admin/support</td>
<td>14.6%</td>
</tr>
<tr class="odd">
<td>ICT</td>
<td>15.3%</td>
</tr>
<tr class="even">
<td>Retail</td>
<td>16.6%</td>
</tr>
</tbody>
</table>
<p><strong>Mining/quarrying</strong> and <strong>agriculture</strong> top the list — physically heavy, geographically embedded sectors where proximity to the resource base forces local purchasing. This is consistent with Y&amp;H’s strong agricultural and extractive presence in North Yorkshire, East Riding, and North/Northeast Lincolnshire identified in Section A.</p>
<p><strong>Health/social work</strong> at just 12.9% is Y&amp;H’s least locally-sourced sector, and notably this is <strong>17.9 percentage points below the UK regional mean</strong> (30.8%). This is the single largest negative deviation of any Y&amp;H sector from its UK average, suggesting Y&amp;H’s health sector is unusually dependent on supply chains that reach outside the region — possibly reflecting centralised NHS procurement patterns or a lack of local medical supply/pharmaceutical capacity.</p>
</section>
<section id="yhs-position-relative-to-other-regions-sector-by-sector" class="level3">
<h3 class="anchored" data-anchor-id="yhs-position-relative-to-other-regions-sector-by-sector">3. Y&amp;H’s position relative to other regions: sector-by-sector</h3>
<p>Comparing Y&amp;H’s sector locality scores to the mean across all GB regions reveals where Y&amp;H over- or under-performs on local sourcing:</p>
<p><strong>Sectors where Y&amp;H sources more locally than average:</strong> - <strong>Public administration/defence</strong>: +5.7pp above mean on sourcing, +8.7pp on receiving payments - <strong>Mining/quarrying</strong>: +4.2pp above mean on sourcing, +29.5pp on receiving (driven by Y&amp;H’s concentrated extractive clusters) - <strong>Agriculture</strong>: +2.6pp above mean on sourcing</p>
<p><strong>Sectors where Y&amp;H sources substantially less locally than average:</strong> - <strong>Health/social work</strong>: −17.9pp (the biggest gap — see above) - <strong>Power/energy</strong>: −15.0pp - <strong>Admin/support services</strong>: −7.9pp - <strong>ICT</strong>: −6.0pp - <strong>Food/beverage service</strong>: −5.0pp - <strong>Transport</strong>: −4.3pp</p>
<p>The <strong>power/energy</strong> gap (−15.0pp) is striking. Y&amp;H’s energy sector purchases are overwhelmingly non-local despite the presence of significant energy infrastructure in North/Northeast Lincolnshire. This likely reflects the nationally-integrated nature of energy markets and the dominance of a few large corporate entities.</p>
<p><strong>Finance/insurance</strong> in Y&amp;H shows an interesting pattern: payer locality is below average (−3.3pp on sourcing), but payee locality is dramatically below average (−9.7pp on receiving). Y&amp;H’s finance sector — anchored by Leeds as noted in Section A — buys its inputs somewhat non-locally, but receives an even smaller share of its payments from local sources. This is consistent with Leeds operating as a national back-office and processing centre: its financial sector serves a geographically dispersed customer base rather than a purely regional one.</p>
</section>
<section id="the-tradeablenon-tradeable-distinction-in-intermediate-supply-chains" class="level3">
<h3 class="anchored" data-anchor-id="the-tradeablenon-tradeable-distinction-in-intermediate-supply-chains">4. The tradeable/non-tradeable distinction in intermediate supply chains</h3>
<p>A key finding from this analysis is that <strong>the traditional distinction between “tradeable” and “non-tradeable” sectors looks different through the lens of B2B supply chains than it does through the lens of final demand</strong>.</p>
<p>Sectors often classified as “non-tradeable” because their output is consumed locally — retail, food service, construction — show <strong>moderate to low locality in their intermediate purchasing</strong>. Retail, in particular, is among the least local sectors on the payer (sourcing) side (18.6% mean across regions), reflecting nationalised wholesale distribution, centralised corporate procurement, and supply chains that pass through major distribution hubs regardless of where the final sale occurs.</p>
<p>The most consistently local linkages across the UK are: - Power → Entertainment (92.7% local) - Other services → Mining/quarrying (92.4%) - Water → Entertainment (92.3%) - Mining/quarrying → Water (88.0%) - Public/defence → Public/defence (83.8%)</p>
<p>These are dominated by utility and public-sector linkages — sectors where the infrastructure itself is place-bound.</p>
<p>The most consistently non-local linkages are: - Finance/insurance → Power (8.6% local) - Public/defence → Finance/insurance (9.3%) - Transport → Power (10.6%)</p>
<p>Finance and power consistently anchor the non-local end of the spectrum.</p>
<p><strong>Implication for Y&amp;H:</strong> The sector catalogue (Section A) identifies retail, food/beverage services, and accommodation as important local employers across Y&amp;H. But this supply chain analysis reveals that these sectors’ intermediate purchasing is largely non-local. Even where they employ people locally and serve local customers, their supply chains pull money out of the region. This complicates the “foundational economy” argument that investing in everyday services necessarily strengthens local economic circuits — it may strengthen local employment without strengthening local supply chains.</p>
</section>
<section id="change-over-time-2019-2025-arrow-plot-analysis" class="level3">
<h3 class="anchored" data-anchor-id="change-over-time-2019-2025-arrow-plot-analysis">5. Change over time: 2019 → 2025 (arrow plot analysis)</h3>
<p>The arrow plot tracks how each sector’s position in the locality scatter has moved between 2019 and 2025. A “compass” classification captures whether sectors became more local on both dimensions (NE/green), less local on both (SW/red), or mixed.</p>
<p><strong>Across all GB regions</strong>, the dominant direction of change is <strong>toward greater locality</strong>: - 60.3% of sector-region combinations moved NE (more local on both dimensions) - 16.7% moved SE (more local sourcing, less local payments received) - 10.0% moved NW (less local sourcing, more local payments) - 12.9% moved SW (less local on both)</p>
<p><strong>For Y&amp;H specifically</strong>, the picture is even more strongly tilted toward localisation: - <strong>68.4%</strong> of sectors moved NE (more local on both) - 10.5% moved SE - 5.3% moved NW - <strong>15.8%</strong> moved SW (3 sectors became less local on both)</p>
<p><strong>Y&amp;H sectors showing the strongest moves toward greater locality:</strong> - <strong>Public administration/defence</strong>: massive shift (+19.1pp on sourcing, +53.8pp on receiving). This is the largest single move in the dataset and likely reflects a structural change in how public sector procurement is recorded or operates in Y&amp;H. - <strong>Mining/quarrying</strong>: +11.8pp on sourcing, already from a high base — becoming even more locally embedded. - <strong>Real estate</strong>: +7.4pp sourcing, +7.2pp receiving — becoming more local on both dimensions. - <strong>Food/beverage service</strong>: +5.9pp sourcing, +7.4pp receiving — moving toward greater local embeddedness, interesting given Section A’s finding that Y&amp;H food/beverage employment has recovered well post-COVID. - <strong>Construction</strong>: +4.1pp sourcing, +7.1pp receiving — consistent with Section A’s finding of growing specialised construction activity in South Yorkshire.</p>
<p><strong>Y&amp;H sectors moving away from locality:</strong> - <strong>Finance/insurance</strong>: −8.4pp on sourcing, −1.2pp on receiving. Y&amp;H’s finance sector is becoming less locally sourced, even as Leeds continues to grow as a financial centre. This is consistent with increasing integration into national/international financial supply chains. - <strong>Agriculture</strong>: −4.9pp on sourcing, −14.1pp on receiving. While Y&amp;H agriculture still sources relatively locally, it is receiving a substantially smaller share of its payments from local sources — suggesting that Y&amp;H agricultural output is increasingly sold into non-local supply chains. - <strong>Water/waste</strong>: −3.9pp on sourcing, −3.4pp on receiving. A modest retreat from locality.</p>
</section>
<section id="connecting-supply-chain-locality-to-the-sector-catalogue-findings" class="level3">
<h3 class="anchored" data-anchor-id="connecting-supply-chain-locality-to-the-sector-catalogue-findings">6. Connecting supply chain locality to the sector catalogue findings</h3>
<p>Several findings from the supply chain analysis directly enrich the sector catalogue interpretation:</p>
<p><strong>Manufacturing</strong> (Section A: Y&amp;H’s diversified manufacturing base): Y&amp;H manufacturing’s intermediate sourcing locality (28.4%) is almost exactly at the UK regional mean (28.0%). This is a sector where Y&amp;H is neither unusually local nor unusually national in its purchasing patterns — despite having strong manufacturing clusters. The implication is that Y&amp;H’s manufacturing strengths (metals, chemicals, food processing) are plugged into national supply chains rather than forming a distinctively self-contained local manufacturing ecosystem.</p>
<p><strong>The logistics corridor</strong> (Section A: Wakefield–Doncaster–Rotherham belt): Transport in Y&amp;H shows below-average payer locality (23.0% vs 27.2% mean) and below-average payee locality (37.0% vs 42.6%). The transport/logistics sector in Y&amp;H is, by its nature, a conduit for moving goods between regions — so it would be surprising if it were highly local. But the below-average scores suggest Y&amp;H’s logistics growth is particularly oriented toward serving national rather than regional distribution needs.</p>
<p><strong>Financial services</strong> (Section A: Y&amp;H second only to Scotland ex-London): The supply chain data confirms that Y&amp;H’s finance sector operates as a nationally-integrated node. Its payee locality of just 4.3% — receiving almost no payments from local sources — is the lowest of any sector in Y&amp;H and far below the 14.0% UK mean. Leeds’ financial centre is genuinely national in reach, which is a strength for the region’s position but means this sector’s multiplier effects on local supply chains are limited.</p>
<p><strong>Construction and specialised construction</strong> (Section A: South Yorkshire strength): Construction in Y&amp;H sources 31.3% locally and receives 50.8% of payments locally — the latter being above the UK mean (48.4%). This is one of the few sectors where Y&amp;H performs above average on receiving local payments, consistent with construction being driven by local demand (housing, infrastructure, commercial development). The growing specialised construction clusters in Barnsley, Doncaster, and Rotherham may be reinforcing this local purchasing pattern.</p>
</section>
<section id="structural-observations" class="level3">
<h3 class="anchored" data-anchor-id="structural-observations">7. Structural observations</h3>
<p><strong>The London effect dominates everything.</strong> London’s 45.9% self-sufficiency score means that nearly half of all inter-industry payments in London stay in London. No other region comes close. This creates a structural asymmetry where London’s economic density generates self-reinforcing internal supply chains, while other regions — including Y&amp;H — are more dependent on inter-regional trade. Regional policy discussions about “keeping money local” need to reckon with the fact that London achieves this through sheer scale and diversity, not through policy.</p>
<p><strong>The overall trend is toward greater locality, not less.</strong> Contrary to a globalisation narrative of ever-more-dispersed supply chains, the 2019–2025 data shows 60% of sector-region combinations becoming more locally embedded. This may reflect post-COVID supply chain adjustments, cost pressures favouring shorter supply chains, or structural changes in how digital services reduce the distance-sensitivity of some transactions while increasing the local share of others.</p>
<p><strong>Finance and power are the universal non-local sectors.</strong> Across all regions, financial services and energy anchor the bottom-left corner of the locality scatter — national markets where regional boundaries matter least for intermediate purchasing. This is a structural feature of how these industries operate (centralised energy markets, nationally-regulated financial services) rather than a regional weakness.</p>
<hr>
<p><em>Plots saved to <code>llm_output/io_plots/</code> — 7 plots covering regional self-sufficiency, sector heatmaps, locality crosshairs, faceted views by sector and region, temporal change arrows, and the local/tradeable linkage matrix.</em></p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>